// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/bitcoin-sv/arc/broadcaster"
	"github.com/libsv/go-bt/v2"
	"github.com/libsv/go-bt/v2/bscript"
	"sync"
)

// Ensure, that UtxoClientMock does implement broadcaster.UtxoClient.
// If this is not the case, regenerate this file with moq.
var _ broadcaster.UtxoClient = &UtxoClientMock{}

// UtxoClientMock is a mock implementation of broadcaster.UtxoClient.
//
//	func TestSomethingThatUsesUtxoClient(t *testing.T) {
//
//		// make and configure a mocked broadcaster.UtxoClient
//		mockedUtxoClient := &UtxoClientMock{
//			GetUTXOsFunc: func(mainnet bool, lockingScript *bscript.Script, address string) ([]*bt.UTXO, error) {
//				panic("mock out the GetUTXOs method")
//			},
//		}
//
//		// use mockedUtxoClient in code that requires broadcaster.UtxoClient
//		// and then make assertions.
//
//	}
type UtxoClientMock struct {
	// GetUTXOsFunc mocks the GetUTXOs method.
	GetUTXOsFunc func(mainnet bool, lockingScript *bscript.Script, address string) ([]*bt.UTXO, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetUTXOs holds details about calls to the GetUTXOs method.
		GetUTXOs []struct {
			// Mainnet is the mainnet argument value.
			Mainnet bool
			// LockingScript is the lockingScript argument value.
			LockingScript *bscript.Script
			// Address is the address argument value.
			Address string
		}
	}
	lockGetUTXOs sync.RWMutex
}

// GetUTXOs calls GetUTXOsFunc.
func (mock *UtxoClientMock) GetUTXOs(mainnet bool, lockingScript *bscript.Script, address string) ([]*bt.UTXO, error) {
	if mock.GetUTXOsFunc == nil {
		panic("UtxoClientMock.GetUTXOsFunc: method is nil but UtxoClient.GetUTXOs was just called")
	}
	callInfo := struct {
		Mainnet       bool
		LockingScript *bscript.Script
		Address       string
	}{
		Mainnet:       mainnet,
		LockingScript: lockingScript,
		Address:       address,
	}
	mock.lockGetUTXOs.Lock()
	mock.calls.GetUTXOs = append(mock.calls.GetUTXOs, callInfo)
	mock.lockGetUTXOs.Unlock()
	return mock.GetUTXOsFunc(mainnet, lockingScript, address)
}

// GetUTXOsCalls gets all the calls that were made to GetUTXOs.
// Check the length with:
//
//	len(mockedUtxoClient.GetUTXOsCalls())
func (mock *UtxoClientMock) GetUTXOsCalls() []struct {
	Mainnet       bool
	LockingScript *bscript.Script
	Address       string
} {
	var calls []struct {
		Mainnet       bool
		LockingScript *bscript.Script
		Address       string
	}
	mock.lockGetUTXOs.RLock()
	calls = mock.calls.GetUTXOs
	mock.lockGetUTXOs.RUnlock()
	return calls
}
