version: "2"
run:
  build-tags:
    - e2e
linters:
  default: none
  enable:
    - asasalint
    - errcheck
    - ineffassign
    - revive
    - staticcheck
    - unused
  settings:
    cyclop:
      max-complexity: 30
      package-average: 10
    errcheck:
      check-type-assertions: true
    exhaustive:
      check:
        - switch
        - map
    funlen:
      lines: 100
      statements: 50
      ignore-comments: true
    gocognit:
      min-complexity: 20
    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    gomodguard:
      blocked:
        modules:
          - github.com/golang/protobuf:
              recommendations:
                - google.golang.org/protobuf
              reason: see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules
          - github.com/satori/go.uuid:
              recommendations:
                - github.com/google/uuid
              reason: satori's package is not maintained
          - github.com/gofrs/uuid:
              recommendations:
                - github.com/google/uuid
              reason: gofrs' package is not go module
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        shadow:
          strict: true
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-no-explanation:
        - funlen
        - gocognit
        - lll
    revive:
      enable-all-rules: true
      rules:
        - name: cognitive-complexity
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: add-constant
          disabled: true
        - name: deep-exit
          disabled: true
        - name: function-length
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: import-alias-naming
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: use-any
          disabled: true
        - name: confusing-results
          disabled: true
        - name: flag-parameter
          disabled: false
        - name: unused-receiver
          disabled: true
        - name: bare-return
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: datarace
          disabled: true
        - name: if-return
          disabled: true
        - name: unhandled-error
          disabled: true
        - name: redundant-import-alias
          disabled: true
        - name: import-shadowing
          disabled: true
        - name: range-val-in-closure
          disabled: true
        - name: defer
          disabled: true
        - name: modifies-value-receiver
          disabled: true
        - name: comment-spacings
          disabled: true
        - name: argument-limit
          disabled: true
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: don't use an underscore in package name
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 50
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
