// Package mapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package mapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for FeeFeeType.
const (
	Data     FeeFeeType = "data"
	Standard FeeFeeType = "standard"
)

// BasicResponse defines model for BasicResponse.
type BasicResponse struct {
	ApiVersion string    `json:"apiVersion"`
	MinerId    string    `json:"minerId"`
	Timestamp  time.Time `json:"timestamp"`
}

// ChainInfo defines model for ChainInfo.
type ChainInfo struct {
	BlockHash   *string `json:"blockHash,omitempty"`
	BlockHeight *uint64 `json:"blockHeight,omitempty"`
}

// An HTTP Problem Details object, as defined in IETF RFC 7807 (https://tools.ietf.org/html/rfc7807).
type Error interface{}

// ErrorBadRequest defines model for ErrorBadRequest.
type ErrorBadRequest struct {
	Detail interface{} `json:"detail"`

	// Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`
	Status    interface{}  `json:"status"`
	Title     interface{}  `json:"title"`

	// Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorConflict defines model for ErrorConflict.
type ErrorConflict struct {
	ConflictedWith *interface{} `json:"conflictedWith,omitempty"`
	Detail         interface{}  `json:"detail"`

	// Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`
	Status    interface{}  `json:"status"`
	Title     interface{}  `json:"title"`

	// Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorFee defines model for ErrorFee.
type ErrorFee struct {
	Detail interface{} `json:"detail"`

	// Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`
	Status    interface{}  `json:"status"`
	Title     interface{}  `json:"title"`

	// Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorFields defines model for ErrorFields.
type ErrorFields struct {
	// Longer description of error
	Detail string `json:"detail"`

	// Optional extra information about the error from the miner
	ExtraInfo *string `json:"extraInfo"`

	// (Optional) Link to actual error on server
	Instance *string `json:"instance"`

	// Error code
	Status int `json:"status"`

	// Descriptive text for error
	Title string `json:"title"`

	// Transaction ID this error is referring to
	Txid *string `json:"txid"`

	// Type of error, with link to more information
	Type string `json:"type"`
}

// ErrorFrozenConsensus defines model for ErrorFrozenConsensus.
type ErrorFrozenConsensus struct {
	Detail interface{} `json:"detail"`

	// Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`
	Status    interface{}  `json:"status"`
	Title     interface{}  `json:"title"`

	// Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorFrozenPolicy defines model for ErrorFrozenPolicy.
type ErrorFrozenPolicy struct {
	Detail interface{} `json:"detail"`

	// Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`
	Status    interface{}  `json:"status"`
	Title     interface{}  `json:"title"`

	// Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorInputs defines model for ErrorInputs.
type ErrorInputs struct {
	Detail interface{} `json:"detail"`

	// Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`
	Status    interface{}  `json:"status"`
	Title     interface{}  `json:"title"`

	// Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorMalformed defines model for ErrorMalformed.
type ErrorMalformed struct {
	Detail interface{} `json:"detail"`

	// Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`
	Status    interface{}  `json:"status"`
	Title     interface{}  `json:"title"`

	// Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorUnlockingScripts defines model for ErrorUnlockingScripts.
type ErrorUnlockingScripts struct {
	Detail interface{} `json:"detail"`

	// Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`
	Status    interface{}  `json:"status"`
	Title     interface{}  `json:"title"`

	// Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// Fee defines model for Fee.
type Fee struct {
	FeeType   FeeFeeType `json:"feeType"`
	MiningFee FeeAmount  `json:"miningFee"`
	RelayFee  FeeAmount  `json:"relayFee"`
}

// FeeFeeType defines model for Fee.FeeType.
type FeeFeeType string

// FeeAmount defines model for FeeAmount.
type FeeAmount struct {
	Bytes    uint64 `json:"bytes"`
	Satoshis uint64 `json:"satoshis"`
}

// FeeQuote defines model for FeeQuote.
type FeeQuote struct {
	ExpiryTime time.Time `json:"expiryTime"`
	Fees       *[]Fee    `json:"fees"`
}

// Policy defines model for Policy.
type Policy struct {
	ApiVersion string           `json:"apiVersion"`
	ExpiryTime time.Time        `json:"expiryTime"`
	Fees       *[]Fee           `json:"fees"`
	MinerId    string           `json:"minerId"`
	Policies   *Policy_Policies `json:"policies"`
	Timestamp  time.Time        `json:"timestamp"`
}

// Policy_Policies defines model for Policy.Policies.
type Policy_Policies struct {
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	ApiVersion  string    `json:"apiVersion"`
	BlockHash   *string   `json:"blockHash,omitempty"`
	BlockHeight *uint64   `json:"blockHeight,omitempty"`
	MinerId     string    `json:"minerId"`
	Timestamp   time.Time `json:"timestamp"`
	Tx          string    `json:"tx"`
	Txid        string    `json:"txid"`
}

// TransactionDetails defines model for TransactionDetails.
type TransactionDetails struct {
	ConflictedWith *[]string `json:"conflictedWith"`
	Status         int       `json:"status"`
	Title          string    `json:"title"`

	// Transaction ID in hex
	Txid *string `json:"txid,omitempty"`
}

// TransactionResponse defines model for TransactionResponse.
type TransactionResponse struct {
	ApiVersion     string    `json:"apiVersion"`
	BlockHash      *string   `json:"blockHash,omitempty"`
	BlockHeight    *uint64   `json:"blockHeight,omitempty"`
	ConflictedWith *[]string `json:"conflictedWith"`
	MinerId        string    `json:"minerId"`
	Status         int       `json:"status"`
	Timestamp      time.Time `json:"timestamp"`
	Title          string    `json:"title"`

	// Transaction ID in hex
	Txid *string `json:"txid,omitempty"`
}

// TransactionResponses defines model for TransactionResponses.
type TransactionResponses struct {
	ApiVersion   string         `json:"apiVersion"`
	BlockHash    *string        `json:"blockHash,omitempty"`
	BlockHeight  *uint64        `json:"blockHeight,omitempty"`
	MinerId      string         `json:"minerId"`
	Timestamp    time.Time      `json:"timestamp"`
	Transactions *[]interface{} `json:"transactions,omitempty"`
}

// TransactionStatus defines model for TransactionStatus.
type TransactionStatus struct {
	ApiVersion  string    `json:"apiVersion"`
	BlockHash   *string   `json:"blockHash,omitempty"`
	BlockHeight *uint64   `json:"blockHeight,omitempty"`
	MinerId     string    `json:"minerId"`
	Timestamp   time.Time `json:"timestamp"`
	Txid        string    `json:"txid"`
}

// TransactionSubmitStatus defines model for TransactionSubmitStatus.
type TransactionSubmitStatus struct {
	Status int    `json:"status"`
	Title  string `json:"title"`
}

// CallbackToken defines model for callbackToken.
type CallbackToken = string

// CallbackUrl defines model for callbackUrl.
type CallbackUrl = string

// MerkleProof defines model for merkleProof.
type MerkleProof = string

// PostMapiV2TxJSONBody defines parameters for PostMapiV2Tx.
type PostMapiV2TxJSONBody = string

// PostMapiV2TxParams defines parameters for PostMapiV2Tx.
type PostMapiV2TxParams struct {
	// Default double spend and merkle proof notification callback endpoint.
	XCallbackUrl *CallbackUrl `json:"X-CallbackUrl,omitempty"`

	// Access token for notification callback endpoint.
	XCallbackToken *CallbackToken `json:"X-CallbackToken,omitempty"`

	// Whether to include merkle proofs in the callbacks (true | false).
	XMerkleProof *MerkleProof `json:"X-MerkleProof,omitempty"`
}

// PostMapiV2TxsJSONBody defines parameters for PostMapiV2Txs.
type PostMapiV2TxsJSONBody = []string

// PostMapiV2TxsParams defines parameters for PostMapiV2Txs.
type PostMapiV2TxsParams struct {
	// Default double spend and merkle proof notification callback endpoint.
	XCallbackUrl *CallbackUrl `json:"X-CallbackUrl,omitempty"`

	// Access token for notification callback endpoint.
	XCallbackToken *CallbackToken `json:"X-CallbackToken,omitempty"`

	// Whether to include merkle proofs in the callbacks (true | false).
	XMerkleProof *MerkleProof `json:"X-MerkleProof,omitempty"`
}

// PostMapiV2TxJSONRequestBody defines body for PostMapiV2Tx for application/json ContentType.
type PostMapiV2TxJSONRequestBody = PostMapiV2TxJSONBody

// PostMapiV2TxsJSONRequestBody defines body for PostMapiV2Txs for application/json ContentType.
type PostMapiV2TxsJSONRequestBody = PostMapiV2TxsJSONBody

// Getter for additional properties for Policy_Policies. Returns the specified
// element and whether it was found
func (a Policy_Policies) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Policy_Policies
func (a *Policy_Policies) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Policy_Policies to handle AdditionalProperties
func (a *Policy_Policies) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Policy_Policies to handle AdditionalProperties
func (a Policy_Policies) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetMapiV2Policy request
	GetMapiV2Policy(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostMapiV2Tx request with any body
	PostMapiV2TxWithBody(ctx context.Context, params *PostMapiV2TxParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostMapiV2Tx(ctx context.Context, params *PostMapiV2TxParams, body PostMapiV2TxJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMapiV2TxId request
	GetMapiV2TxId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMapiV2TxStatusId request
	GetMapiV2TxStatusId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostMapiV2Txs request with any body
	PostMapiV2TxsWithBody(ctx context.Context, params *PostMapiV2TxsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostMapiV2Txs(ctx context.Context, params *PostMapiV2TxsParams, body PostMapiV2TxsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetMapiV2Policy(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMapiV2PolicyRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostMapiV2TxWithBody(ctx context.Context, params *PostMapiV2TxParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostMapiV2TxRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostMapiV2Tx(ctx context.Context, params *PostMapiV2TxParams, body PostMapiV2TxJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostMapiV2TxRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMapiV2TxId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMapiV2TxIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMapiV2TxStatusId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMapiV2TxStatusIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostMapiV2TxsWithBody(ctx context.Context, params *PostMapiV2TxsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostMapiV2TxsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostMapiV2Txs(ctx context.Context, params *PostMapiV2TxsParams, body PostMapiV2TxsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostMapiV2TxsRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetMapiV2PolicyRequest generates requests for GetMapiV2Policy
func NewGetMapiV2PolicyRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/mapi/v2/policy")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostMapiV2TxRequest calls the generic PostMapiV2Tx builder with application/json body
func NewPostMapiV2TxRequest(server string, params *PostMapiV2TxParams, body PostMapiV2TxJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostMapiV2TxRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostMapiV2TxRequestWithBody generates requests for PostMapiV2Tx with any type of body
func NewPostMapiV2TxRequestWithBody(server string, params *PostMapiV2TxParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/mapi/v2/tx")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params.XCallbackUrl != nil {
		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-CallbackUrl", runtime.ParamLocationHeader, *params.XCallbackUrl)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-CallbackUrl", headerParam0)
	}

	if params.XCallbackToken != nil {
		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithLocation("simple", false, "X-CallbackToken", runtime.ParamLocationHeader, *params.XCallbackToken)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-CallbackToken", headerParam1)
	}

	if params.XMerkleProof != nil {
		var headerParam2 string

		headerParam2, err = runtime.StyleParamWithLocation("simple", false, "X-MerkleProof", runtime.ParamLocationHeader, *params.XMerkleProof)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-MerkleProof", headerParam2)
	}

	return req, nil
}

// NewGetMapiV2TxIdRequest generates requests for GetMapiV2TxId
func NewGetMapiV2TxIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/mapi/v2/tx/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMapiV2TxStatusIdRequest generates requests for GetMapiV2TxStatusId
func NewGetMapiV2TxStatusIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/mapi/v2/txStatus/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostMapiV2TxsRequest calls the generic PostMapiV2Txs builder with application/json body
func NewPostMapiV2TxsRequest(server string, params *PostMapiV2TxsParams, body PostMapiV2TxsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostMapiV2TxsRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostMapiV2TxsRequestWithBody generates requests for PostMapiV2Txs with any type of body
func NewPostMapiV2TxsRequestWithBody(server string, params *PostMapiV2TxsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/mapi/v2/txs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params.XCallbackUrl != nil {
		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-CallbackUrl", runtime.ParamLocationHeader, *params.XCallbackUrl)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-CallbackUrl", headerParam0)
	}

	if params.XCallbackToken != nil {
		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithLocation("simple", false, "X-CallbackToken", runtime.ParamLocationHeader, *params.XCallbackToken)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-CallbackToken", headerParam1)
	}

	if params.XMerkleProof != nil {
		var headerParam2 string

		headerParam2, err = runtime.StyleParamWithLocation("simple", false, "X-MerkleProof", runtime.ParamLocationHeader, *params.XMerkleProof)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-MerkleProof", headerParam2)
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetMapiV2Policy request
	GetMapiV2PolicyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMapiV2PolicyResponse, error)

	// PostMapiV2Tx request with any body
	PostMapiV2TxWithBodyWithResponse(ctx context.Context, params *PostMapiV2TxParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostMapiV2TxResponse, error)

	PostMapiV2TxWithResponse(ctx context.Context, params *PostMapiV2TxParams, body PostMapiV2TxJSONRequestBody, reqEditors ...RequestEditorFn) (*PostMapiV2TxResponse, error)

	// GetMapiV2TxId request
	GetMapiV2TxIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetMapiV2TxIdResponse, error)

	// GetMapiV2TxStatusId request
	GetMapiV2TxStatusIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetMapiV2TxStatusIdResponse, error)

	// PostMapiV2Txs request with any body
	PostMapiV2TxsWithBodyWithResponse(ctx context.Context, params *PostMapiV2TxsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostMapiV2TxsResponse, error)

	PostMapiV2TxsWithResponse(ctx context.Context, params *PostMapiV2TxsParams, body PostMapiV2TxsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostMapiV2TxsResponse, error)
}

type GetMapiV2PolicyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Policy
}

// Status returns HTTPResponse.Status
func (r GetMapiV2PolicyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMapiV2PolicyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostMapiV2TxResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TransactionResponse
	JSON201      *TransactionResponse
	JSON400      *ErrorBadRequest
	JSON402      *ErrorFee
	JSON409      *ErrorConflict
	JSON422      *Error
}

// Status returns HTTPResponse.Status
func (r PostMapiV2TxResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostMapiV2TxResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMapiV2TxIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Transaction
}

// Status returns HTTPResponse.Status
func (r GetMapiV2TxIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMapiV2TxIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMapiV2TxStatusIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TransactionStatus
}

// Status returns HTTPResponse.Status
func (r GetMapiV2TxStatusIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMapiV2TxStatusIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostMapiV2TxsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TransactionResponses
	JSON400      *ErrorBadRequest
}

// Status returns HTTPResponse.Status
func (r PostMapiV2TxsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostMapiV2TxsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetMapiV2PolicyWithResponse request returning *GetMapiV2PolicyResponse
func (c *ClientWithResponses) GetMapiV2PolicyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMapiV2PolicyResponse, error) {
	rsp, err := c.GetMapiV2Policy(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMapiV2PolicyResponse(rsp)
}

// PostMapiV2TxWithBodyWithResponse request with arbitrary body returning *PostMapiV2TxResponse
func (c *ClientWithResponses) PostMapiV2TxWithBodyWithResponse(ctx context.Context, params *PostMapiV2TxParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostMapiV2TxResponse, error) {
	rsp, err := c.PostMapiV2TxWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostMapiV2TxResponse(rsp)
}

func (c *ClientWithResponses) PostMapiV2TxWithResponse(ctx context.Context, params *PostMapiV2TxParams, body PostMapiV2TxJSONRequestBody, reqEditors ...RequestEditorFn) (*PostMapiV2TxResponse, error) {
	rsp, err := c.PostMapiV2Tx(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostMapiV2TxResponse(rsp)
}

// GetMapiV2TxIdWithResponse request returning *GetMapiV2TxIdResponse
func (c *ClientWithResponses) GetMapiV2TxIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetMapiV2TxIdResponse, error) {
	rsp, err := c.GetMapiV2TxId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMapiV2TxIdResponse(rsp)
}

// GetMapiV2TxStatusIdWithResponse request returning *GetMapiV2TxStatusIdResponse
func (c *ClientWithResponses) GetMapiV2TxStatusIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetMapiV2TxStatusIdResponse, error) {
	rsp, err := c.GetMapiV2TxStatusId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMapiV2TxStatusIdResponse(rsp)
}

// PostMapiV2TxsWithBodyWithResponse request with arbitrary body returning *PostMapiV2TxsResponse
func (c *ClientWithResponses) PostMapiV2TxsWithBodyWithResponse(ctx context.Context, params *PostMapiV2TxsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostMapiV2TxsResponse, error) {
	rsp, err := c.PostMapiV2TxsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostMapiV2TxsResponse(rsp)
}

func (c *ClientWithResponses) PostMapiV2TxsWithResponse(ctx context.Context, params *PostMapiV2TxsParams, body PostMapiV2TxsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostMapiV2TxsResponse, error) {
	rsp, err := c.PostMapiV2Txs(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostMapiV2TxsResponse(rsp)
}

// ParseGetMapiV2PolicyResponse parses an HTTP response from a GetMapiV2PolicyWithResponse call
func ParseGetMapiV2PolicyResponse(rsp *http.Response) (*GetMapiV2PolicyResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMapiV2PolicyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Policy
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostMapiV2TxResponse parses an HTTP response from a PostMapiV2TxWithResponse call
func ParsePostMapiV2TxResponse(rsp *http.Response) (*PostMapiV2TxResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostMapiV2TxResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TransactionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest TransactionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorBadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 402:
		var dest ErrorFee
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON402 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorConflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetMapiV2TxIdResponse parses an HTTP response from a GetMapiV2TxIdWithResponse call
func ParseGetMapiV2TxIdResponse(rsp *http.Response) (*GetMapiV2TxIdResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMapiV2TxIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Transaction
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetMapiV2TxStatusIdResponse parses an HTTP response from a GetMapiV2TxStatusIdWithResponse call
func ParseGetMapiV2TxStatusIdResponse(rsp *http.Response) (*GetMapiV2TxStatusIdResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMapiV2TxStatusIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TransactionStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostMapiV2TxsResponse parses an HTTP response from a PostMapiV2TxsWithResponse call
func ParsePostMapiV2TxsResponse(rsp *http.Response) (*PostMapiV2TxsResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostMapiV2TxsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TransactionResponses
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorBadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get the miner policy
	// (GET /mapi/v2/policy)
	GetMapiV2Policy(ctx echo.Context) error
	// Submit a transaction.
	// (POST /mapi/v2/tx)
	PostMapiV2Tx(ctx echo.Context, params PostMapiV2TxParams) error
	// Query transaction
	// (GET /mapi/v2/tx/{id})
	GetMapiV2TxId(ctx echo.Context, id string) error
	// Query transaction status.
	// (GET /mapi/v2/txStatus/{id})
	GetMapiV2TxStatusId(ctx echo.Context, id string) error
	// Submit multiple transactions.
	// (POST /mapi/v2/txs)
	PostMapiV2Txs(ctx echo.Context, params PostMapiV2TxsParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetMapiV2Policy converts echo context to params.
func (w *ServerInterfaceWrapper) GetMapiV2Policy(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetMapiV2Policy(ctx)
	return err
}

// PostMapiV2Tx converts echo context to params.
func (w *ServerInterfaceWrapper) PostMapiV2Tx(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostMapiV2TxParams

	headers := ctx.Request().Header
	// ------------- Optional header parameter "X-CallbackUrl" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CallbackUrl")]; found {
		var XCallbackUrl CallbackUrl
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-CallbackUrl, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-CallbackUrl", runtime.ParamLocationHeader, valueList[0], &XCallbackUrl)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-CallbackUrl: %s", err))
		}

		params.XCallbackUrl = &XCallbackUrl
	}
	// ------------- Optional header parameter "X-CallbackToken" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CallbackToken")]; found {
		var XCallbackToken CallbackToken
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-CallbackToken, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-CallbackToken", runtime.ParamLocationHeader, valueList[0], &XCallbackToken)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-CallbackToken: %s", err))
		}

		params.XCallbackToken = &XCallbackToken
	}
	// ------------- Optional header parameter "X-MerkleProof" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-MerkleProof")]; found {
		var XMerkleProof MerkleProof
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-MerkleProof, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-MerkleProof", runtime.ParamLocationHeader, valueList[0], &XMerkleProof)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-MerkleProof: %s", err))
		}

		params.XMerkleProof = &XMerkleProof
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostMapiV2Tx(ctx, params)
	return err
}

// GetMapiV2TxId converts echo context to params.
func (w *ServerInterfaceWrapper) GetMapiV2TxId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetMapiV2TxId(ctx, id)
	return err
}

// GetMapiV2TxStatusId converts echo context to params.
func (w *ServerInterfaceWrapper) GetMapiV2TxStatusId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetMapiV2TxStatusId(ctx, id)
	return err
}

// PostMapiV2Txs converts echo context to params.
func (w *ServerInterfaceWrapper) PostMapiV2Txs(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostMapiV2TxsParams

	headers := ctx.Request().Header
	// ------------- Optional header parameter "X-CallbackUrl" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CallbackUrl")]; found {
		var XCallbackUrl CallbackUrl
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-CallbackUrl, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-CallbackUrl", runtime.ParamLocationHeader, valueList[0], &XCallbackUrl)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-CallbackUrl: %s", err))
		}

		params.XCallbackUrl = &XCallbackUrl
	}
	// ------------- Optional header parameter "X-CallbackToken" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CallbackToken")]; found {
		var XCallbackToken CallbackToken
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-CallbackToken, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-CallbackToken", runtime.ParamLocationHeader, valueList[0], &XCallbackToken)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-CallbackToken: %s", err))
		}

		params.XCallbackToken = &XCallbackToken
	}
	// ------------- Optional header parameter "X-MerkleProof" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-MerkleProof")]; found {
		var XMerkleProof MerkleProof
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-MerkleProof, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-MerkleProof", runtime.ParamLocationHeader, valueList[0], &XMerkleProof)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-MerkleProof: %s", err))
		}

		params.XMerkleProof = &XMerkleProof
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostMapiV2Txs(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/mapi/v2/policy", wrapper.GetMapiV2Policy)
	router.POST(baseURL+"/mapi/v2/tx", wrapper.PostMapiV2Tx)
	router.GET(baseURL+"/mapi/v2/tx/:id", wrapper.GetMapiV2TxId)
	router.GET(baseURL+"/mapi/v2/txStatus/:id", wrapper.GetMapiV2TxStatusId)
	router.POST(baseURL+"/mapi/v2/txs", wrapper.PostMapiV2Txs)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RbW3Pbtrb+Kxie85DMyBIvEiX5LXHqU880rRu77Zmd+gEEFkU0JMACoCs12/99D8CL",
	"SImSJVtu0u4+1SLBdV/41iWfHSKyXHDgWjnnn50cS5yBBmn/IjhNI0w+3YpPwM0PFBSRLNdMcOfceUMI",
	"KIW0eYpiIREXmsWMYPMc1YcRcJoLxvXQGTjMnEsAU5DOwOE4A+fc+f+ziw6hgaNIAhk2FPUqN68oLRlf",
	"OA8Pg4apn2S6zdI7iHGRakRFEaWAVA6cIswpykB+SgHlUoj4+Xwa2vu5LOldG3LbXP6SgE5AIi0Q4yQt",
	"KHT4U4hxpBNoWFPolZYFoH+jGKcKXu/h8H2L7j4OHwaOBJULrsCa+nuh3xQ6EZL9CXSb4xsghWR6hST8",
	"XjAJmXEYFGOWArXylpTsp95ixciH6uPWqaTIQWpWUsI5+xmkst/97MASZ3lqWLv3h+7QdQabrA6cjHGQ",
	"V7T7uhvA3KcBTEgQTyM6H09oHMXjGUzxfB7Mg8iL4iiIPS8OZi6GwKX+LIRpHPsYyAT7015SmmWgNM5y",
	"QywWMsPaOXco1nBmHm0fsXq0KqHO+ce2cO2PrWW4a74got+AaEP0IsGMX/FYbCsrSgX59C1WSY8NB9VT",
	"YItEd/gtGNfheM0s4xoWIC23W9S/kVLInuDm6Nvb22t0LUWUQobegcYsVag8OEBYIQox40CNt159c3uJ",
	"PlxeoOnMnaJXida5Oh+NtBCpGjLQ8VDIxSjRWTqSMTEvWScWHH6InfOPn53/lRA7587/jNb5aFT51Mhy",
	"+BM3wjK+uLFMKudhcMCpK54Xh777HqdGg8ahD3n9Uoo/gV+LlJHVMScuTFhwVSjn4a5W/1tMP8DvBShr",
	"R5ymh2rlkkFKS/m6jkOtubohc5uAjV9QGimAzKRuFAHKasFtpiSYc6HN77kUJsFbhTiMK405ge4na0Nn",
	"OGdDjXE6JCIbgWFNjTw/GE8moTmtNNaF6pwdu64NOJ1ufPMtpjWbTuOwO4lGTBPBuLpvUx67bp+z3+1y",
	"/wvB45SRk2mfVN8D+gvTSYf7j47rBx4de8GETAj2wJ26UUjcgHrx3Iv9eEYoJmPqUXC9KPRnc0qnJJxh",
	"GoWzCQ7nkWPcpte+S8QUuscpowMUFdrcIRLMbxjVHDG+QHpZXzA2gSANWZ5iDc8xc7DTyvN+K190GYpF",
	"wenTzT0/ytyXAC8dZzFArWQtMVeYWLDBTMwJlIo/qtir7n+bRHFpj+eYwd9pBr/fDJcANUdP175/nPZL",
	"XZ7vVmX3JvpO8AVI1PoRiRhZ4s7gdGof9uEBWGqJ66u5y9YP9n9wiuw7iPHy+jXkcCTK6Cu5RLEUmf3T",
	"ogAD14o0xZHh2uC6Hrpt+3fJvqrpvkbfMf7JyIOJLgwflpbgSIG8P4zM2lO6RKydEBEU2hoeu/5gDTIY",
	"1z0Io+Vkm8i8+usekIaltgVDbcRtHLZkPSj0tmXSq3dIJ0xVUjOFJMQgpU0n4hDZa1ffILHKoXGvAfqD",
	"6QSllZ4zYbLp2s6PokH7tNZIo+0mee+OkA2g8IK5ygIkVBJEr6IUk08pUxplmGMTdaRmAjXPgL5+kRQ1",
	"3ZGi2iw+OUdNj8xRbXD3BdWfWw7+At17L6l77yjdV5j9JS9oC5QYt1AJRUBwocAmaGZpIywBccHPYGl0",
	"zjUS0vYS9IsoP9zp+CWDrC5inqb+8DjXX5dBL26BrFVxvYBag361NgK2IcLTtRscpd2tMvaLuHlhuUDl",
	"xVe6e/Xay1jC2+/gRa2UmqOnW+PgVFPXAJSyEk9dt/Rp22yDDRXHALc1T7zIzAVv9ESxpOZOxxq3bvRO",
	"94rxRUVun4EvAd5koiiTjIQUr447tAE+anbbHLS+u0Mn1ceO00y00pWKHu1ADRyFtVAJUwd3rNpCNYcH",
	"FdEdYvxYCH2sfWGZM7m6ZRkc2vwbGCXbs0xDpg6wlTmzA5liKfFqS+AWUxW1PomPBSrdFu1jzatGn9tp",
	"x+KTurHbq+rPuyWu+d8QufnmtqR3D4N2EfBSAq8bsubNI1xIL3v7tHU180i1YN4yLz8ueNWMPVz+1tmb",
	"IsqYvinT9CGtq8a39xZjjKMElp2CnE6pT8KJN6d4Frk+9mEaTkgUkHkwG4d0TsOAzD0SzCCaRdMZmdJp",
	"RMYhYOJP/NmkN+D2B8+BhWMPr2FEIxLjyJ34IQ1cmNFw5k/n8XRO4zj04mjs+iEmMIumUeBPZ3Mcu14Y",
	"BCFMxrEfu7214PY1tGXvvmhucdseo+z1w5cPgwPdq3bNTZf90J42fV1Bu2aym8sPm070yX7INKDU0Fby",
	"3x/4Nw26+sry3sEJ7tHc1slPW03CHnjpu94xbal1zL+h1BQBAmWQ5UKkj/ZzmgZO+bG7vptMVZPSG6PT",
	"kue3gCXIN0WZTruZqXyGcKET4LqeSXeHax8uL1A4nbj1QNdQjOy5NccGG5djXVZ1K1NGoMoc1XT4hxw4",
	"envzM/quejRwCpm2gHWFqbFSgjDLyZCDHokc+Fmk7s+qT45a+nTM996/ub5yBs59PdZ1ylHuw8AxR3HO",
	"nHMnGLpDzxk4OdaJ1YqF8aN7f5Q34GUBuid32y5fNZtHEnQhuVp3U1ENF+zwyiAkRBIsF0DtgDEHaQW5",
	"os6583+g3+Oc/exXeGljBu67bnUDmpq/nFXnaWWT0W+qBBzrmfq+UKrngg92VtMZpRd2bcJoZ+wGu77T",
	"MDbqTubtqfG2lr4Xup6hGCcssgzLVSnypq6M3BovlPFoow7nzhxpzFFimFyoR23BFCpUGUHK7lkgif/o",
	"9N21QLgiHQtZdt2VbciXPXoOS10PoRLc5pRIwBrUEKHbBFC554DW2ymIYI4iaOiLe5CS0bK6XaQiwilS",
	"oDXjC7tNsRKFtG6KKFZJJLCkliOdgOqMCtS211wLVbnN7dI68HpFZkf2Xb8yam+r7Eq/Pa+XizAHHGjv",
	"mdQAA5R+K+jqKF9eZ8VfC9cNSNuKCSxRmRHts/4tiPbnBdGgz5SWgLMuma47aVC6g8K2aUeMY7lCprre",
	"Q1zDUo/yFLPTSrW1JXNYhqio2hP11WLYaoLyTSoB05VxzPXVc4/TAjYXZNZbMc0SzIk2X9aLLo7v+v6Z",
	"5555s1svOA/cc98fhpPgX04Np5+Pjh+qNR7ar4jy0aM6aG3DOO7mfx6dxeMo8seUzgM6hrlHYO6HhEzx",
	"fOpF4Hoz4kczOg7peBLHzsb6zDT0ZuHs76/nh8GBN1RflbH/uvJd70jvV9XhrtFr2LWxffCPD4FTm2aX",
	"Ii1GOB2U2dxQ6uFkY2Vn7PqnpW47Z9tkN5YXngqn5qdltlkm6uG4s/XSuoya9Zexf2LV9XHxE69Wu3CU",
	"AjJ1h16hs3LY3d3kKxcB2uVNE8ZlnYZwW47hY9By9JnRhwOhfgteLsAQyiXcM1GodIWUJa67M5w9gP92",
	"eUW3sdsm9e7SyNU79CrwUbTSgBKsktctyFAv4JpqZr1+a/t364Kx7FDt3sG9e8H6o90l/eJFyI8FyFVn",
	"2vaIm5TV/xOdhSRg6wlApJASuEZl3Y5E/FwnKvn673Wlumv81TlUZeJH8496am2bFalmeQqbJa46RY37",
	"VZW46h9b4zaN3eeVhT1N28OK36+jzv2Vf6laGBu8+veuBTqjgo/rdrTtQdct0d1CnayWsHkN6n+5sdZn",
	"GxH/XXRYr648e2+6vbly0LrKelvFrrbW9usq8VQ267TqD9iovjtNz+QrMfJf0bpZB6PbCsYNdZ0yBJ9T",
	"0PeiqFZjsJs7BkhIhDuiHFzlN5fDRqg97Z8CHRlkk7ATZS3DtHsGR8WGHSydrHWxr959Gpbtq5Ib+LiJ",
	"wzbRamuCaOOmPTv8ePdw9/CfAAAA///+VmncsjsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
