version: '3'

env:
  REPOSITORY: github.com/bitcoin-sv/arc
  APP_COMMIT:
    sh: git rev-parse --short HEAD
  APP_VERSION:
    sh: git describe --tags --always --abbrev=0 --match='v[0-9]*.[0-9]*.[0-9]*' 2> /dev/null | sed 's/^.//'

tasks:
  default:
    cmds: [task:deps, task:lint, task:build, task:test]

  deps:
    cmds: [go mod download]

  build:
    cmds: [go build ./...]

  build_release:
    cmds:
      - mkdir -p build
      - |
        CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags "-X {{.REPOSITORY}}/internal/version.Commit={{.APP_COMMIT}} -X {{.REPOSITORY}}/internal/version.Version={{.APP_VERSION}}" -o build/arc_linux_amd64 ./cmd/arc/main.go

  build_docker:
    cmds:
      - docker build . -t test-arc --build-arg="APP_COMMIT={{.APP_COMMIT}}" --build-arg="APP_VERSION={{.APP_VERSION}}"

  run:
    cmds:
      - task:build_docker
      - docker compose --env-file ./.env.dev up blocktx callbacker metamorph api

  run_e2e_tests:
    cmds:
      - task:build_docker
      - docker compose --env-file ./.env.dev up blocktx callbacker metamorph api tests --scale blocktx=2 --scale metamorph=2 --exit-code-from tests
      - docker compose down

  run_e2e_tests_with_tracing:
    cmds:
      - task:build_docker
      - ARC_TRACING_ENABLED=TRUE docker compose --env-file ./.env.dev up blocktx callbacker metamorph api tests jaeger --scale blocktx=2 --scale metamorph=2 --no-attach jaeger

  run_e2e_mcast_tests:
    cmds:
      - task:build_docker
      - docker compose -f docker-compose-mcast.yaml --env-file ./.env.dev up mcast_sidecar blocktx metamorph api tests --scale blocktx=6 --exit-code-from tests
      - docker compose -f docker-compose-mcast.yaml down

  test:
    cmds:
      - CGO_ENABLED=1 go test -ldflags="-w -s" -coverprofile=./cov.out -covermode=atomic -race -count=1 ./... -coverpkg ./...

  test_short:
    cmds:
      - go test -coverprofile=./cov_short.out -covermode=atomic -race -short -count=1 ./... -coverpkg ./...

  coverage:
    cmds:
      - go tool cover -html=cov.out -o coverage_report.html
      - goverreport -coverprofile cov.out -packages -sort block

  coverage_short:
    cmds:
      - go tool cover -html=cov_short.out -o coverage_report_short.html
      - goverreport -coverprofile cov_short.out -packages -sort block

  install_lint:
    cmds: [go install honnef.co/go/tools/cmd/staticcheck@2025.1.1]

  lint:
    cmds:
      - golangci-lint run -v ./...
      - staticcheck ./...

  lint_fix:
    cmds: [golangci-lint run -v ./... --fix]

  gen_go:
    cmds: [go generate ./...]

  gen:
    cmds:
      - |
        protoc \
        --proto_path=. \
        --go_out=. \
        --go_opt=paths=source_relative \
        --go-grpc_out=. \
        --go-grpc_opt=paths=source_relative \
        internal/metamorph/metamorph_api/metamorph_api.proto

      - |
        protoc \
        --proto_path=. \
        --go_out=. \
        --go_opt=paths=source_relative \
        --go-grpc_out=. \
        --go-grpc_opt=paths=source_relative \
        internal/blocktx/blocktx_api/blocktx_api.proto

      - |
        protoc \
        --proto_path=. \
        --go_out=. \
        --go_opt=paths=source_relative \
        --go-grpc_out=. \
        --go-grpc_opt=paths=source_relative \
        internal/callbacker/callbacker_api/callbacker_api.proto

      - |
        protoc \
        --proto_path=. \
        --go_out=. \
        --go_opt=paths=source_relative \
        --go-grpc_out=. \
        --go-grpc_opt=paths=source_relative \
        pkg/message_queue/nats/client/test_api/test_api.proto

  clean_gen:
    cmds:
      - rm -f ./internal/metamorph/metamorph_api/*.pb.go
      - rm -f ./internal/blocktx/blocktx_api/*.pb.go
      - rm -f ./internal/callbacker/callbacker_api/*.pb.go

  install_coverage:
    cmds:
      - go install github.com/mcubik/goverreport@latest
      - go install github.com/jstemmer/go-junit-report/v2@latest

  clean:
    cmds: [rm -rf build/]

  install:
    cmds:
      - brew install pre-commit
      - pre-commit install
      - pre-commit install --hook-type commit-msg

  install_gen:
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.6
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
      - go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.4.1
      - go install github.com/matryer/moq@v0.5.3

  docs:
    cmds: [sh scripts/generate_docs.sh]

  gh-pages:
    cmds:
      - git push --force origin `git subtree split --prefix doc master`:gh-pages

  api:
    cmds: [oapi-codegen -config pkg/api/config.yaml pkg/api/arc.yaml > pkg/api/arc.go]

  compare_config:
    cmds:
      - rm -f ./config/dumped_config.yaml
      - go run ./cmd/arc/main.go -dump_config "./config/dumped_config.yaml"
      - go run ./scripts/compare_yamls.go
      - rm ./config/dumped_config.yaml
