// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	Api_KeyScopes       = "Api_Key.Scopes"
	AuthorizationScopes = "Authorization.Scopes"
	BearerAuthScopes    = "BearerAuth.Scopes"
)

// Defines values for TransactionDetailsTxStatus.
const (
	ANNOUNCEDTONETWORK TransactionDetailsTxStatus = "ANNOUNCED_TO_NETWORK"
	CONFIRMED          TransactionDetailsTxStatus = "CONFIRMED"
	MINED              TransactionDetailsTxStatus = "MINED"
	RECEIVED           TransactionDetailsTxStatus = "RECEIVED"
	REJECTED           TransactionDetailsTxStatus = "REJECTED"
	REQUESTEDBYNETWORK TransactionDetailsTxStatus = "REQUESTED_BY_NETWORK"
	SEENONNETWORK      TransactionDetailsTxStatus = "SEEN_ON_NETWORK"
	SENTTONETWORK      TransactionDetailsTxStatus = "SENT_TO_NETWORK"
	STORED             TransactionDetailsTxStatus = "STORED"
	UNKNOWN            TransactionDetailsTxStatus = "UNKNOWN"
)

// ChainInfo Chain info
type ChainInfo struct {
	// BlockHash Block hash
	BlockHash *string `json:"blockHash,omitempty"`

	// BlockHeight Block height
	BlockHeight *uint64 `json:"blockHeight,omitempty"`
}

// CommonResponse Common response object
type CommonResponse struct {
	Timestamp time.Time `json:"timestamp"`
}

// Error An HTTP Problem Details object, as defined in IETF RFC 7807 (https://tools.ietf.org/html/rfc7807).
type Error struct {
	union json.RawMessage
}

// ErrorBadRequest defines model for ErrorBadRequest.
type ErrorBadRequest struct {
	Detail interface{} `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`

	// Status Error code
	Status int `json:"status"`

	// Txid Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorFee defines model for ErrorFee.
type ErrorFee struct {
	Detail interface{} `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`

	// Status Error code
	Status int `json:"status"`

	// Txid Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorFields defines model for ErrorFields.
type ErrorFields struct {
	// Detail Longer description of error
	Detail string `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string `json:"extraInfo"`

	// Instance (Optional) Link to actual error on server
	Instance *string `json:"instance"`

	// Status Error code
	Status int `json:"status"`

	// Txid Transaction ID this error is referring to
	Txid *string `json:"txid"`

	// Type Type of error, with link to more information
	Type string `json:"type"`
}

// ErrorFrozenConsensus defines model for ErrorFrozenConsensus.
type ErrorFrozenConsensus struct {
	Detail interface{} `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`

	// Status Error code
	Status int `json:"status"`

	// Txid Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorFrozenPolicy defines model for ErrorFrozenPolicy.
type ErrorFrozenPolicy struct {
	Detail interface{} `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`

	// Status Error code
	Status int `json:"status"`

	// Txid Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorGeneric defines model for ErrorGeneric.
type ErrorGeneric struct {
	Detail interface{} `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`

	// Status Error code
	Status int `json:"status"`

	// Txid Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorInputs defines model for ErrorInputs.
type ErrorInputs struct {
	Detail interface{} `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`

	// Status Error code
	Status int `json:"status"`

	// Txid Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorMalformed defines model for ErrorMalformed.
type ErrorMalformed struct {
	Detail interface{} `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`

	// Status Error code
	Status int `json:"status"`

	// Txid Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorNotFound defines model for ErrorNotFound.
type ErrorNotFound struct {
	Detail interface{} `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`

	// Status Error code
	Status int `json:"status"`

	// Txid Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorOutputs defines model for ErrorOutputs.
type ErrorOutputs struct {
	Detail interface{} `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`

	// Status Error code
	Status int `json:"status"`

	// Txid Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorTxFormat defines model for ErrorTxFormat.
type ErrorTxFormat struct {
	Detail interface{} `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`

	// Status Error code
	Status int `json:"status"`

	// Txid Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorUnlockingScripts defines model for ErrorUnlockingScripts.
type ErrorUnlockingScripts struct {
	Detail interface{} `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`

	// Status Error code
	Status int `json:"status"`

	// Txid Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// FeeAmount defines model for FeeAmount.
type FeeAmount struct {
	// Bytes Number of bytes
	Bytes uint64 `json:"bytes"`

	// Satoshis Amount in Satoshis
	Satoshis uint64 `json:"satoshis"`
}

// Health healthy or not
type Health struct {
	// Healthy whether healthy or not
	Healthy *bool `json:"healthy,omitempty"`

	// Reason explains the problem with metamorph
	Reason *string `json:"reason"`
}

// Policy defines model for Policy.
type Policy struct {
	// Maxscriptsizepolicy Maximum script size [bytes]
	Maxscriptsizepolicy uint64 `json:"maxscriptsizepolicy"`

	// Maxtxsigopscountspolicy Maximum number of signature operations
	Maxtxsigopscountspolicy uint64 `json:"maxtxsigopscountspolicy"`

	// Maxtxsizepolicy Maximum transaction size [bytes]
	Maxtxsizepolicy uint64    `json:"maxtxsizepolicy"`
	MiningFee       FeeAmount `json:"miningFee"`
}

// PolicyResponse defines model for PolicyResponse.
type PolicyResponse struct {
	Policy    Policy    `json:"policy"`
	Timestamp time.Time `json:"timestamp"`
}

// TransactionDetails defines model for TransactionDetails.
type TransactionDetails struct {
	// ExtraInfo Extra information about the transaction
	ExtraInfo *string `json:"extraInfo"`

	// MerklePath Transaction Merkle path as a hex string in BUMP format [BRC-74](https://brc.dev/74)
	MerklePath *string `json:"merklePath"`

	// TxStatus Transaction status
	TxStatus *TransactionDetailsTxStatus `json:"txStatus,omitempty"`

	// Txid Transaction ID in hex
	Txid *string `json:"txid,omitempty"`
}

// TransactionDetailsTxStatus Transaction status
type TransactionDetailsTxStatus string

// TransactionRequest defines model for TransactionRequest.
type TransactionRequest struct {
	// RawTx Raw hex string
	RawTx string `json:"rawTx"`
}

// TransactionResponse defines model for TransactionResponse.
type TransactionResponse struct {
	// BlockHash Block hash
	BlockHash *string `json:"blockHash,omitempty"`

	// BlockHeight Block height
	BlockHeight *uint64 `json:"blockHeight,omitempty"`

	// ExtraInfo Extra info
	ExtraInfo *string `json:"extraInfo"`

	// MerklePath Transaction Merkle path as a hex string in  BUMP format [BRC-74](https://brc.dev/74)
	MerklePath *string   `json:"merklePath"`
	Timestamp  time.Time `json:"timestamp"`

	// TxStatus Transaction status
	TxStatus string `json:"txStatus"`

	// Txid Transaction ID in hex
	Txid string `json:"txid"`
}

// TransactionResponses defines model for TransactionResponses.
type TransactionResponses struct {
	// BlockHash Block hash
	BlockHash *string `json:"blockHash,omitempty"`

	// BlockHeight Block height
	BlockHeight  *uint64                                   `json:"blockHeight,omitempty"`
	Timestamp    time.Time                                 `json:"timestamp"`
	Transactions *[]TransactionResponses_Transactions_Item `json:"transactions,omitempty"`
}

// TransactionResponses_Transactions_Item defines model for TransactionResponses.transactions.Item.
type TransactionResponses_Transactions_Item struct {
	union json.RawMessage
}

// TransactionStatus defines model for TransactionStatus.
type TransactionStatus struct {
	// BlockHash Block hash
	BlockHash *string `json:"blockHash,omitempty"`

	// BlockHeight Block height
	BlockHeight *uint64 `json:"blockHeight,omitempty"`

	// ExtraInfo Extra information about the transaction
	ExtraInfo *string `json:"extraInfo"`

	// MerklePath Transaction Merkle path as a hex string in BUMP format [BRC-74](https://brc.dev/74)
	MerklePath *string   `json:"merklePath"`
	Timestamp  time.Time `json:"timestamp"`

	// TxStatus Transaction status
	TxStatus *string `json:"txStatus,omitempty"`

	// Txid Transaction ID in hex
	Txid string `json:"txid"`
}

// CallbackToken defines model for callbackToken.
type CallbackToken = string

// CallbackUrl defines model for callbackUrl.
type CallbackUrl = string

// FullStatusUpdates defines model for fullStatusUpdates.
type FullStatusUpdates = bool

// MaxTimeout defines model for maxTimeout.
type MaxTimeout = int

// SkipFeeValidation defines model for skipFeeValidation.
type SkipFeeValidation = bool

// SkipScriptValidation defines model for skipScriptValidation.
type SkipScriptValidation = bool

// SkipTxValidation defines model for skipTxValidation.
type SkipTxValidation = bool

// WaitForStatus defines model for waitForStatus.
type WaitForStatus = int

// POSTTransactionTextBody defines parameters for POSTTransaction.
type POSTTransactionTextBody = string

// POSTTransactionParams defines parameters for POSTTransaction.
type POSTTransactionParams struct {
	// XCallbackUrl Default double spend and merkle proof notification callback endpoint.
	XCallbackUrl *CallbackUrl `json:"X-CallbackUrl,omitempty"`

	// XFullStatusUpdates Whether we should have full status updates in callback or not (including SEEN_IN_ORPHAN_MEMPOOL and SEEN_ON_NETWORK statuses).
	XFullStatusUpdates *FullStatusUpdates `json:"X-FullStatusUpdates,omitempty"`

	// XMaxTimeout Timeout in seconds to wait for new transaction status before request expires (max 30 seconds, default 5)
	XMaxTimeout *MaxTimeout `json:"X-MaxTimeout,omitempty"`

	// XSkipFeeValidation Whether we should skip fee validation or not.
	XSkipFeeValidation *SkipFeeValidation `json:"X-SkipFeeValidation,omitempty"`

	// XSkipScriptValidation Whether we should skip script validation or not.
	XSkipScriptValidation *SkipScriptValidation `json:"X-SkipScriptValidation,omitempty"`

	// XSkipTxValidation Whether we should skip overall tx validation or not.
	XSkipTxValidation *SkipTxValidation `json:"X-SkipTxValidation,omitempty"`

	// XCallbackToken Access token for notification callback endpoint. It will be used as a Authorization header for the http callback
	XCallbackToken *CallbackToken `json:"X-CallbackToken,omitempty"`

	// XWaitForStatus Which status to wait for from the server before returning (2 = RECEIVED, 3 = STORED, 4 = ANNOUNCED_TO_NETWORK, 5 = REQUESTED_BY_NETWORK, 6 = SENT_TO_NETWORK, 7 = ACCEPTED_BY_NETWORK, 8 = SEEN_ON_NETWORK)
	XWaitForStatus *WaitForStatus `json:"X-WaitForStatus,omitempty"`
}

// POSTTransactionsJSONBody defines parameters for POSTTransactions.
type POSTTransactionsJSONBody = []TransactionRequest

// POSTTransactionsTextBody defines parameters for POSTTransactions.
type POSTTransactionsTextBody = string

// POSTTransactionsParams defines parameters for POSTTransactions.
type POSTTransactionsParams struct {
	// XCallbackUrl Default double spend and merkle proof notification callback endpoint.
	XCallbackUrl *CallbackUrl `json:"X-CallbackUrl,omitempty"`

	// XFullStatusUpdates Whether we should have full status updates in callback or not (including SEEN_IN_ORPHAN_MEMPOOL and SEEN_ON_NETWORK statuses).
	XFullStatusUpdates *FullStatusUpdates `json:"X-FullStatusUpdates,omitempty"`

	// XMaxTimeout Timeout in seconds to wait for new transaction status before request expires (max 30 seconds, default 5)
	XMaxTimeout *MaxTimeout `json:"X-MaxTimeout,omitempty"`

	// XSkipFeeValidation Whether we should skip fee validation or not.
	XSkipFeeValidation *SkipFeeValidation `json:"X-SkipFeeValidation,omitempty"`

	// XSkipScriptValidation Whether we should skip script validation or not.
	XSkipScriptValidation *SkipScriptValidation `json:"X-SkipScriptValidation,omitempty"`

	// XSkipTxValidation Whether we should skip overall tx validation or not.
	XSkipTxValidation *SkipTxValidation `json:"X-SkipTxValidation,omitempty"`

	// XCallbackToken Access token for notification callback endpoint. It will be used as a Authorization header for the http callback
	XCallbackToken *CallbackToken `json:"X-CallbackToken,omitempty"`

	// XWaitForStatus Which status to wait for from the server before returning (2 = RECEIVED, 3 = STORED, 4 = ANNOUNCED_TO_NETWORK, 5 = REQUESTED_BY_NETWORK, 6 = SENT_TO_NETWORK, 7 = ACCEPTED_BY_NETWORK, 8 = SEEN_ON_NETWORK)
	XWaitForStatus *WaitForStatus `json:"X-WaitForStatus,omitempty"`
}

// POSTTransactionJSONRequestBody defines body for POSTTransaction for application/json ContentType.
type POSTTransactionJSONRequestBody = TransactionRequest

// POSTTransactionTextRequestBody defines body for POSTTransaction for text/plain ContentType.
type POSTTransactionTextRequestBody = POSTTransactionTextBody

// POSTTransactionsJSONRequestBody defines body for POSTTransactions for application/json ContentType.
type POSTTransactionsJSONRequestBody = POSTTransactionsJSONBody

// POSTTransactionsTextRequestBody defines body for POSTTransactions for text/plain ContentType.
type POSTTransactionsTextRequestBody = POSTTransactionsTextBody

// AsErrorUnlockingScripts returns the union data inside the Error as a ErrorUnlockingScripts
func (t Error) AsErrorUnlockingScripts() (ErrorUnlockingScripts, error) {
	var body ErrorUnlockingScripts
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorUnlockingScripts overwrites any union data inside the Error as the provided ErrorUnlockingScripts
func (t *Error) FromErrorUnlockingScripts(v ErrorUnlockingScripts) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorUnlockingScripts performs a merge with any union data inside the Error, using the provided ErrorUnlockingScripts
func (t *Error) MergeErrorUnlockingScripts(v ErrorUnlockingScripts) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorInputs returns the union data inside the Error as a ErrorInputs
func (t Error) AsErrorInputs() (ErrorInputs, error) {
	var body ErrorInputs
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorInputs overwrites any union data inside the Error as the provided ErrorInputs
func (t *Error) FromErrorInputs(v ErrorInputs) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorInputs performs a merge with any union data inside the Error, using the provided ErrorInputs
func (t *Error) MergeErrorInputs(v ErrorInputs) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorMalformed returns the union data inside the Error as a ErrorMalformed
func (t Error) AsErrorMalformed() (ErrorMalformed, error) {
	var body ErrorMalformed
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorMalformed overwrites any union data inside the Error as the provided ErrorMalformed
func (t *Error) FromErrorMalformed(v ErrorMalformed) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorMalformed performs a merge with any union data inside the Error, using the provided ErrorMalformed
func (t *Error) MergeErrorMalformed(v ErrorMalformed) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorFrozenPolicy returns the union data inside the Error as a ErrorFrozenPolicy
func (t Error) AsErrorFrozenPolicy() (ErrorFrozenPolicy, error) {
	var body ErrorFrozenPolicy
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorFrozenPolicy overwrites any union data inside the Error as the provided ErrorFrozenPolicy
func (t *Error) FromErrorFrozenPolicy(v ErrorFrozenPolicy) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorFrozenPolicy performs a merge with any union data inside the Error, using the provided ErrorFrozenPolicy
func (t *Error) MergeErrorFrozenPolicy(v ErrorFrozenPolicy) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorFrozenConsensus returns the union data inside the Error as a ErrorFrozenConsensus
func (t Error) AsErrorFrozenConsensus() (ErrorFrozenConsensus, error) {
	var body ErrorFrozenConsensus
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorFrozenConsensus overwrites any union data inside the Error as the provided ErrorFrozenConsensus
func (t *Error) FromErrorFrozenConsensus(v ErrorFrozenConsensus) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorFrozenConsensus performs a merge with any union data inside the Error, using the provided ErrorFrozenConsensus
func (t *Error) MergeErrorFrozenConsensus(v ErrorFrozenConsensus) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t Error) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Error) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsTransactionDetails returns the union data inside the TransactionResponses_Transactions_Item as a TransactionDetails
func (t TransactionResponses_Transactions_Item) AsTransactionDetails() (TransactionDetails, error) {
	var body TransactionDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTransactionDetails overwrites any union data inside the TransactionResponses_Transactions_Item as the provided TransactionDetails
func (t *TransactionResponses_Transactions_Item) FromTransactionDetails(v TransactionDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTransactionDetails performs a merge with any union data inside the TransactionResponses_Transactions_Item, using the provided TransactionDetails
func (t *TransactionResponses_Transactions_Item) MergeTransactionDetails(v TransactionDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsError returns the union data inside the TransactionResponses_Transactions_Item as a Error
func (t TransactionResponses_Transactions_Item) AsError() (Error, error) {
	var body Error
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromError overwrites any union data inside the TransactionResponses_Transactions_Item as the provided Error
func (t *TransactionResponses_Transactions_Item) FromError(v Error) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeError performs a merge with any union data inside the TransactionResponses_Transactions_Item, using the provided Error
func (t *TransactionResponses_Transactions_Item) MergeError(v Error) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t TransactionResponses_Transactions_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TransactionResponses_Transactions_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GETHealth request
	GETHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GETPolicy request
	GETPolicy(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// POSTTransactionWithBody request with any body
	POSTTransactionWithBody(ctx context.Context, params *POSTTransactionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	POSTTransaction(ctx context.Context, params *POSTTransactionParams, body POSTTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	POSTTransactionWithTextBody(ctx context.Context, params *POSTTransactionParams, body POSTTransactionTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GETTransactionStatus request
	GETTransactionStatus(ctx context.Context, txid string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// POSTTransactionsWithBody request with any body
	POSTTransactionsWithBody(ctx context.Context, params *POSTTransactionsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	POSTTransactions(ctx context.Context, params *POSTTransactionsParams, body POSTTransactionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	POSTTransactionsWithTextBody(ctx context.Context, params *POSTTransactionsParams, body POSTTransactionsTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GETHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGETHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GETPolicy(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGETPolicyRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) POSTTransactionWithBody(ctx context.Context, params *POSTTransactionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPOSTTransactionRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) POSTTransaction(ctx context.Context, params *POSTTransactionParams, body POSTTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPOSTTransactionRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) POSTTransactionWithTextBody(ctx context.Context, params *POSTTransactionParams, body POSTTransactionTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPOSTTransactionRequestWithTextBody(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GETTransactionStatus(ctx context.Context, txid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGETTransactionStatusRequest(c.Server, txid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) POSTTransactionsWithBody(ctx context.Context, params *POSTTransactionsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPOSTTransactionsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) POSTTransactions(ctx context.Context, params *POSTTransactionsParams, body POSTTransactionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPOSTTransactionsRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) POSTTransactionsWithTextBody(ctx context.Context, params *POSTTransactionsParams, body POSTTransactionsTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPOSTTransactionsRequestWithTextBody(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGETHealthRequest generates requests for GETHealth
func NewGETHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGETPolicyRequest generates requests for GETPolicy
func NewGETPolicyRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/policy")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPOSTTransactionRequest calls the generic POSTTransaction builder with application/json body
func NewPOSTTransactionRequest(server string, params *POSTTransactionParams, body POSTTransactionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPOSTTransactionRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPOSTTransactionRequestWithTextBody calls the generic POSTTransaction builder with text/plain body
func NewPOSTTransactionRequestWithTextBody(server string, params *POSTTransactionParams, body POSTTransactionTextRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyReader = strings.NewReader(string(body))
	return NewPOSTTransactionRequestWithBody(server, params, "text/plain", bodyReader)
}

// NewPOSTTransactionRequestWithBody generates requests for POSTTransaction with any type of body
func NewPOSTTransactionRequestWithBody(server string, params *POSTTransactionParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/tx")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XCallbackUrl != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-CallbackUrl", runtime.ParamLocationHeader, *params.XCallbackUrl)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-CallbackUrl", headerParam0)
		}

		if params.XFullStatusUpdates != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithLocation("simple", false, "X-FullStatusUpdates", runtime.ParamLocationHeader, *params.XFullStatusUpdates)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-FullStatusUpdates", headerParam1)
		}

		if params.XMaxTimeout != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithLocation("simple", false, "X-MaxTimeout", runtime.ParamLocationHeader, *params.XMaxTimeout)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-MaxTimeout", headerParam2)
		}

		if params.XSkipFeeValidation != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithLocation("simple", false, "X-SkipFeeValidation", runtime.ParamLocationHeader, *params.XSkipFeeValidation)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-SkipFeeValidation", headerParam3)
		}

		if params.XSkipScriptValidation != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithLocation("simple", false, "X-SkipScriptValidation", runtime.ParamLocationHeader, *params.XSkipScriptValidation)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-SkipScriptValidation", headerParam4)
		}

		if params.XSkipTxValidation != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithLocation("simple", false, "X-SkipTxValidation", runtime.ParamLocationHeader, *params.XSkipTxValidation)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-SkipTxValidation", headerParam5)
		}

		if params.XCallbackToken != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithLocation("simple", false, "X-CallbackToken", runtime.ParamLocationHeader, *params.XCallbackToken)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-CallbackToken", headerParam6)
		}

		if params.XWaitForStatus != nil {
			var headerParam7 string

			headerParam7, err = runtime.StyleParamWithLocation("simple", false, "X-WaitForStatus", runtime.ParamLocationHeader, *params.XWaitForStatus)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-WaitForStatus", headerParam7)
		}

	}

	return req, nil
}

// NewGETTransactionStatusRequest generates requests for GETTransactionStatus
func NewGETTransactionStatusRequest(server string, txid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "txid", runtime.ParamLocationPath, txid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/tx/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPOSTTransactionsRequest calls the generic POSTTransactions builder with application/json body
func NewPOSTTransactionsRequest(server string, params *POSTTransactionsParams, body POSTTransactionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPOSTTransactionsRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPOSTTransactionsRequestWithTextBody calls the generic POSTTransactions builder with text/plain body
func NewPOSTTransactionsRequestWithTextBody(server string, params *POSTTransactionsParams, body POSTTransactionsTextRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyReader = strings.NewReader(string(body))
	return NewPOSTTransactionsRequestWithBody(server, params, "text/plain", bodyReader)
}

// NewPOSTTransactionsRequestWithBody generates requests for POSTTransactions with any type of body
func NewPOSTTransactionsRequestWithBody(server string, params *POSTTransactionsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/txs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XCallbackUrl != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-CallbackUrl", runtime.ParamLocationHeader, *params.XCallbackUrl)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-CallbackUrl", headerParam0)
		}

		if params.XFullStatusUpdates != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithLocation("simple", false, "X-FullStatusUpdates", runtime.ParamLocationHeader, *params.XFullStatusUpdates)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-FullStatusUpdates", headerParam1)
		}

		if params.XMaxTimeout != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithLocation("simple", false, "X-MaxTimeout", runtime.ParamLocationHeader, *params.XMaxTimeout)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-MaxTimeout", headerParam2)
		}

		if params.XSkipFeeValidation != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithLocation("simple", false, "X-SkipFeeValidation", runtime.ParamLocationHeader, *params.XSkipFeeValidation)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-SkipFeeValidation", headerParam3)
		}

		if params.XSkipScriptValidation != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithLocation("simple", false, "X-SkipScriptValidation", runtime.ParamLocationHeader, *params.XSkipScriptValidation)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-SkipScriptValidation", headerParam4)
		}

		if params.XSkipTxValidation != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithLocation("simple", false, "X-SkipTxValidation", runtime.ParamLocationHeader, *params.XSkipTxValidation)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-SkipTxValidation", headerParam5)
		}

		if params.XCallbackToken != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithLocation("simple", false, "X-CallbackToken", runtime.ParamLocationHeader, *params.XCallbackToken)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-CallbackToken", headerParam6)
		}

		if params.XWaitForStatus != nil {
			var headerParam7 string

			headerParam7, err = runtime.StyleParamWithLocation("simple", false, "X-WaitForStatus", runtime.ParamLocationHeader, *params.XWaitForStatus)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-WaitForStatus", headerParam7)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GETHealthWithResponse request
	GETHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GETHealthResponse, error)

	// GETPolicyWithResponse request
	GETPolicyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GETPolicyResponse, error)

	// POSTTransactionWithBodyWithResponse request with any body
	POSTTransactionWithBodyWithResponse(ctx context.Context, params *POSTTransactionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*POSTTransactionResponse, error)

	POSTTransactionWithResponse(ctx context.Context, params *POSTTransactionParams, body POSTTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*POSTTransactionResponse, error)

	POSTTransactionWithTextBodyWithResponse(ctx context.Context, params *POSTTransactionParams, body POSTTransactionTextRequestBody, reqEditors ...RequestEditorFn) (*POSTTransactionResponse, error)

	// GETTransactionStatusWithResponse request
	GETTransactionStatusWithResponse(ctx context.Context, txid string, reqEditors ...RequestEditorFn) (*GETTransactionStatusResponse, error)

	// POSTTransactionsWithBodyWithResponse request with any body
	POSTTransactionsWithBodyWithResponse(ctx context.Context, params *POSTTransactionsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*POSTTransactionsResponse, error)

	POSTTransactionsWithResponse(ctx context.Context, params *POSTTransactionsParams, body POSTTransactionsJSONRequestBody, reqEditors ...RequestEditorFn) (*POSTTransactionsResponse, error)

	POSTTransactionsWithTextBodyWithResponse(ctx context.Context, params *POSTTransactionsParams, body POSTTransactionsTextRequestBody, reqEditors ...RequestEditorFn) (*POSTTransactionsResponse, error)
}

type GETHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Health
}

// Status returns HTTPResponse.Status
func (r GETHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GETHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GETPolicyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PolicyResponse
}

// Status returns HTTPResponse.Status
func (r GETPolicyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GETPolicyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type POSTTransactionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TransactionResponse
	JSON400      *ErrorBadRequest
	JSON409      *ErrorGeneric
	JSON422      *Error
	JSON460      *ErrorTxFormat
	JSON461      *ErrorUnlockingScripts
	JSON462      *ErrorInputs
	JSON463      *ErrorMalformed
	JSON464      *ErrorOutputs
	JSON465      *ErrorFee
}

// Status returns HTTPResponse.Status
func (r POSTTransactionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r POSTTransactionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GETTransactionStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TransactionStatus
	JSON404      *ErrorNotFound
	JSON409      *ErrorGeneric
}

// Status returns HTTPResponse.Status
func (r GETTransactionStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GETTransactionStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type POSTTransactionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TransactionResponses
	JSON400      *ErrorBadRequest
	JSON409      *ErrorGeneric
	JSON460      *ErrorTxFormat
	JSON461      *ErrorUnlockingScripts
	JSON462      *ErrorInputs
	JSON463      *ErrorMalformed
	JSON464      *ErrorOutputs
	JSON465      *ErrorFee
}

// Status returns HTTPResponse.Status
func (r POSTTransactionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r POSTTransactionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GETHealthWithResponse request returning *GETHealthResponse
func (c *ClientWithResponses) GETHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GETHealthResponse, error) {
	rsp, err := c.GETHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGETHealthResponse(rsp)
}

// GETPolicyWithResponse request returning *GETPolicyResponse
func (c *ClientWithResponses) GETPolicyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GETPolicyResponse, error) {
	rsp, err := c.GETPolicy(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGETPolicyResponse(rsp)
}

// POSTTransactionWithBodyWithResponse request with arbitrary body returning *POSTTransactionResponse
func (c *ClientWithResponses) POSTTransactionWithBodyWithResponse(ctx context.Context, params *POSTTransactionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*POSTTransactionResponse, error) {
	rsp, err := c.POSTTransactionWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePOSTTransactionResponse(rsp)
}

func (c *ClientWithResponses) POSTTransactionWithResponse(ctx context.Context, params *POSTTransactionParams, body POSTTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*POSTTransactionResponse, error) {
	rsp, err := c.POSTTransaction(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePOSTTransactionResponse(rsp)
}

func (c *ClientWithResponses) POSTTransactionWithTextBodyWithResponse(ctx context.Context, params *POSTTransactionParams, body POSTTransactionTextRequestBody, reqEditors ...RequestEditorFn) (*POSTTransactionResponse, error) {
	rsp, err := c.POSTTransactionWithTextBody(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePOSTTransactionResponse(rsp)
}

// GETTransactionStatusWithResponse request returning *GETTransactionStatusResponse
func (c *ClientWithResponses) GETTransactionStatusWithResponse(ctx context.Context, txid string, reqEditors ...RequestEditorFn) (*GETTransactionStatusResponse, error) {
	rsp, err := c.GETTransactionStatus(ctx, txid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGETTransactionStatusResponse(rsp)
}

// POSTTransactionsWithBodyWithResponse request with arbitrary body returning *POSTTransactionsResponse
func (c *ClientWithResponses) POSTTransactionsWithBodyWithResponse(ctx context.Context, params *POSTTransactionsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*POSTTransactionsResponse, error) {
	rsp, err := c.POSTTransactionsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePOSTTransactionsResponse(rsp)
}

func (c *ClientWithResponses) POSTTransactionsWithResponse(ctx context.Context, params *POSTTransactionsParams, body POSTTransactionsJSONRequestBody, reqEditors ...RequestEditorFn) (*POSTTransactionsResponse, error) {
	rsp, err := c.POSTTransactions(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePOSTTransactionsResponse(rsp)
}

func (c *ClientWithResponses) POSTTransactionsWithTextBodyWithResponse(ctx context.Context, params *POSTTransactionsParams, body POSTTransactionsTextRequestBody, reqEditors ...RequestEditorFn) (*POSTTransactionsResponse, error) {
	rsp, err := c.POSTTransactionsWithTextBody(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePOSTTransactionsResponse(rsp)
}

// ParseGETHealthResponse parses an HTTP response from a GETHealthWithResponse call
func ParseGETHealthResponse(rsp *http.Response) (*GETHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GETHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGETPolicyResponse parses an HTTP response from a GETPolicyWithResponse call
func ParseGETPolicyResponse(rsp *http.Response) (*GETPolicyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GETPolicyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PolicyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePOSTTransactionResponse parses an HTTP response from a POSTTransactionWithResponse call
func ParsePOSTTransactionResponse(rsp *http.Response) (*POSTTransactionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &POSTTransactionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TransactionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorBadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorGeneric
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 460:
		var dest ErrorTxFormat
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON460 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 461:
		var dest ErrorUnlockingScripts
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON461 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 462:
		var dest ErrorInputs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON462 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 463:
		var dest ErrorMalformed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON463 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 464:
		var dest ErrorOutputs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON464 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 465:
		var dest ErrorFee
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON465 = &dest

	}

	return response, nil
}

// ParseGETTransactionStatusResponse parses an HTTP response from a GETTransactionStatusWithResponse call
func ParseGETTransactionStatusResponse(rsp *http.Response) (*GETTransactionStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GETTransactionStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TransactionStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorNotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorGeneric
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParsePOSTTransactionsResponse parses an HTTP response from a POSTTransactionsWithResponse call
func ParsePOSTTransactionsResponse(rsp *http.Response) (*POSTTransactionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &POSTTransactionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TransactionResponses
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorBadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorGeneric
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 460:
		var dest ErrorTxFormat
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON460 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 461:
		var dest ErrorUnlockingScripts
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON461 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 462:
		var dest ErrorInputs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON462 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 463:
		var dest ErrorMalformed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON463 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 464:
		var dest ErrorOutputs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON464 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 465:
		var dest ErrorFee
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON465 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get metamorph health
	// (GET /v1/health)
	GETHealth(ctx echo.Context) error
	// Get the policy settings
	// (GET /v1/policy)
	GETPolicy(ctx echo.Context) error
	// Submit a transaction.
	// (POST /v1/tx)
	POSTTransaction(ctx echo.Context, params POSTTransactionParams) error
	// Get transaction status.
	// (GET /v1/tx/{txid})
	GETTransactionStatus(ctx echo.Context, txid string) error
	// Submit multiple transactions.
	// (POST /v1/txs)
	POSTTransactions(ctx echo.Context, params POSTTransactionsParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GETHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GETHealth(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(Api_KeyScopes, []string{})

	ctx.Set(AuthorizationScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GETHealth(ctx)
	return err
}

// GETPolicy converts echo context to params.
func (w *ServerInterfaceWrapper) GETPolicy(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(Api_KeyScopes, []string{})

	ctx.Set(AuthorizationScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GETPolicy(ctx)
	return err
}

// POSTTransaction converts echo context to params.
func (w *ServerInterfaceWrapper) POSTTransaction(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(Api_KeyScopes, []string{})

	ctx.Set(AuthorizationScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params POSTTransactionParams

	headers := ctx.Request().Header
	// ------------- Optional header parameter "X-CallbackUrl" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CallbackUrl")]; found {
		var XCallbackUrl CallbackUrl
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-CallbackUrl, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-CallbackUrl", runtime.ParamLocationHeader, valueList[0], &XCallbackUrl)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-CallbackUrl: %s", err))
		}

		params.XCallbackUrl = &XCallbackUrl
	}
	// ------------- Optional header parameter "X-FullStatusUpdates" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-FullStatusUpdates")]; found {
		var XFullStatusUpdates FullStatusUpdates
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-FullStatusUpdates, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-FullStatusUpdates", runtime.ParamLocationHeader, valueList[0], &XFullStatusUpdates)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-FullStatusUpdates: %s", err))
		}

		params.XFullStatusUpdates = &XFullStatusUpdates
	}
	// ------------- Optional header parameter "X-MaxTimeout" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-MaxTimeout")]; found {
		var XMaxTimeout MaxTimeout
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-MaxTimeout, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-MaxTimeout", runtime.ParamLocationHeader, valueList[0], &XMaxTimeout)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-MaxTimeout: %s", err))
		}

		params.XMaxTimeout = &XMaxTimeout
	}
	// ------------- Optional header parameter "X-SkipFeeValidation" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-SkipFeeValidation")]; found {
		var XSkipFeeValidation SkipFeeValidation
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-SkipFeeValidation, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-SkipFeeValidation", runtime.ParamLocationHeader, valueList[0], &XSkipFeeValidation)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-SkipFeeValidation: %s", err))
		}

		params.XSkipFeeValidation = &XSkipFeeValidation
	}
	// ------------- Optional header parameter "X-SkipScriptValidation" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-SkipScriptValidation")]; found {
		var XSkipScriptValidation SkipScriptValidation
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-SkipScriptValidation, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-SkipScriptValidation", runtime.ParamLocationHeader, valueList[0], &XSkipScriptValidation)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-SkipScriptValidation: %s", err))
		}

		params.XSkipScriptValidation = &XSkipScriptValidation
	}
	// ------------- Optional header parameter "X-SkipTxValidation" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-SkipTxValidation")]; found {
		var XSkipTxValidation SkipTxValidation
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-SkipTxValidation, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-SkipTxValidation", runtime.ParamLocationHeader, valueList[0], &XSkipTxValidation)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-SkipTxValidation: %s", err))
		}

		params.XSkipTxValidation = &XSkipTxValidation
	}
	// ------------- Optional header parameter "X-CallbackToken" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CallbackToken")]; found {
		var XCallbackToken CallbackToken
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-CallbackToken, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-CallbackToken", runtime.ParamLocationHeader, valueList[0], &XCallbackToken)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-CallbackToken: %s", err))
		}

		params.XCallbackToken = &XCallbackToken
	}
	// ------------- Optional header parameter "X-WaitForStatus" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-WaitForStatus")]; found {
		var XWaitForStatus WaitForStatus
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-WaitForStatus, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-WaitForStatus", runtime.ParamLocationHeader, valueList[0], &XWaitForStatus)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-WaitForStatus: %s", err))
		}

		params.XWaitForStatus = &XWaitForStatus
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.POSTTransaction(ctx, params)
	return err
}

// GETTransactionStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GETTransactionStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "txid" -------------
	var txid string

	err = runtime.BindStyledParameterWithLocation("simple", false, "txid", runtime.ParamLocationPath, ctx.Param("txid"), &txid)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter txid: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(Api_KeyScopes, []string{})

	ctx.Set(AuthorizationScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GETTransactionStatus(ctx, txid)
	return err
}

// POSTTransactions converts echo context to params.
func (w *ServerInterfaceWrapper) POSTTransactions(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(Api_KeyScopes, []string{})

	ctx.Set(AuthorizationScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params POSTTransactionsParams

	headers := ctx.Request().Header
	// ------------- Optional header parameter "X-CallbackUrl" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CallbackUrl")]; found {
		var XCallbackUrl CallbackUrl
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-CallbackUrl, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-CallbackUrl", runtime.ParamLocationHeader, valueList[0], &XCallbackUrl)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-CallbackUrl: %s", err))
		}

		params.XCallbackUrl = &XCallbackUrl
	}
	// ------------- Optional header parameter "X-FullStatusUpdates" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-FullStatusUpdates")]; found {
		var XFullStatusUpdates FullStatusUpdates
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-FullStatusUpdates, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-FullStatusUpdates", runtime.ParamLocationHeader, valueList[0], &XFullStatusUpdates)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-FullStatusUpdates: %s", err))
		}

		params.XFullStatusUpdates = &XFullStatusUpdates
	}
	// ------------- Optional header parameter "X-MaxTimeout" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-MaxTimeout")]; found {
		var XMaxTimeout MaxTimeout
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-MaxTimeout, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-MaxTimeout", runtime.ParamLocationHeader, valueList[0], &XMaxTimeout)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-MaxTimeout: %s", err))
		}

		params.XMaxTimeout = &XMaxTimeout
	}
	// ------------- Optional header parameter "X-SkipFeeValidation" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-SkipFeeValidation")]; found {
		var XSkipFeeValidation SkipFeeValidation
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-SkipFeeValidation, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-SkipFeeValidation", runtime.ParamLocationHeader, valueList[0], &XSkipFeeValidation)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-SkipFeeValidation: %s", err))
		}

		params.XSkipFeeValidation = &XSkipFeeValidation
	}
	// ------------- Optional header parameter "X-SkipScriptValidation" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-SkipScriptValidation")]; found {
		var XSkipScriptValidation SkipScriptValidation
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-SkipScriptValidation, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-SkipScriptValidation", runtime.ParamLocationHeader, valueList[0], &XSkipScriptValidation)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-SkipScriptValidation: %s", err))
		}

		params.XSkipScriptValidation = &XSkipScriptValidation
	}
	// ------------- Optional header parameter "X-SkipTxValidation" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-SkipTxValidation")]; found {
		var XSkipTxValidation SkipTxValidation
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-SkipTxValidation, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-SkipTxValidation", runtime.ParamLocationHeader, valueList[0], &XSkipTxValidation)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-SkipTxValidation: %s", err))
		}

		params.XSkipTxValidation = &XSkipTxValidation
	}
	// ------------- Optional header parameter "X-CallbackToken" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CallbackToken")]; found {
		var XCallbackToken CallbackToken
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-CallbackToken, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-CallbackToken", runtime.ParamLocationHeader, valueList[0], &XCallbackToken)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-CallbackToken: %s", err))
		}

		params.XCallbackToken = &XCallbackToken
	}
	// ------------- Optional header parameter "X-WaitForStatus" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-WaitForStatus")]; found {
		var XWaitForStatus WaitForStatus
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-WaitForStatus, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-WaitForStatus", runtime.ParamLocationHeader, valueList[0], &XWaitForStatus)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-WaitForStatus: %s", err))
		}

		params.XWaitForStatus = &XWaitForStatus
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.POSTTransactions(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/v1/health", wrapper.GETHealth)
	router.GET(baseURL+"/v1/policy", wrapper.GETPolicy)
	router.POST(baseURL+"/v1/tx", wrapper.POSTTransaction)
	router.GET(baseURL+"/v1/tx/:txid", wrapper.GETTransactionStatus)
	router.POST(baseURL+"/v1/txs", wrapper.POSTTransactions)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xceW/byJL/Kg2+/SMBZJts3gYGi8Sx33jfxPbayszuZoygj6LVLzy07KYjT+Dvvugm",
	"KZESJUuOcuBt5o+B7b6qqqvr+FUxny1WZNMih1xJ6/izNSUlyUBBaX5jJE0pYR/HxUfI9R84SFaKqRJF",
	"bh1brxgDKZHSoygpSpQXSiSCET2O2sUIcj4tRK4O0blCn0SaIgqoksARkYigV5WaFKX4q141AcKhNLup",
	"CaCJUtP5TtbIEvrceo41snKSgXVs/dfBSY/QkSXZBDKiKVYPUz1FqlLkd9bj42jO1LsyXWXpDSSkShXi",
	"RUVTQHIKOUck5yiD8mMKaFoWRfIUn0/Tqc/eTGVSpemNIqqS76acKJCrtP4xATWBEn0CJCdFlXI0IfeA",
	"9EokzVJU1WuR6JBZ3xN6IXKWVlzkd+jm9PTiw/nFh8vrq19fXXx4e/r26vLyN8O2Gbq8+HBxOv7j8vof",
	"zb4gX25g8myF9AFWaVGkQHLDa0ZmY5FBUalVJpsBzYEEVuRc6xv6RISqNQ4+IVWSXBJmLqPhm0JSlIBK",
	"+N8KpEIwm4oSJHqRkRly7XanEeLNdfsv17PzdkHdAB8iV3AHpeFDfhTTM4DfSSo4qel/+s70IpQAoPv5",
	"suaKNoj4ZuWkJ0SsT7kxdDyDunrKzgSunLcFjePZM+gr7qEkaYrUbGcae+c9QZ9WurOirFV7iDjBJq0C",
	"dnU0KYvMGDMJ5T2UC+VUVZnr9/cCo1/Q9enJ6fnvp29GyEW/oJvx5bX+2UO/oFcXF5fvLk5O33wYX7YP",
	"cYR8s+Y/353ejE/ffHj934uRQK8/vRj3pod6o5OT06vl2ZGZ3XvlGx7DHz0ZbHwPjyOrBDktclkbr4tC",
	"taYe+Kr4boBVpVAP5tGKEjLtklBCRAq8Vg9zlNnqZEJEfp4nxeo2ZggJPTaypmUxhVKJmgCaFuzjr0RO",
	"Vle91kNoosdGFsxINk01M/byf5HvhV5MXeZgn/uYBbHnBmHoex6LSECiyMdeGLs+JRF3Qm6Nli37qKEC",
	"xN1EraWjHu1QEkbYdaKRlRRlRpR1bFUiV4G32L9rhpo/FfSfwJQ+8qTIsiK/bi5jQGZmHLW3hZqVy/JT",
	"IgOpSDbVv8wp0Rb+QA+tMms0wFwmt47fd9bfDhB5WpZFORBj5OjX8fgKXZUFTSFDb0ARkcqGxpEOITgk",
	"IgeuXcT56fgMXZ+doDCyQ/RCRw/y+OhIFUUqDwWo5LAo744mKkuPyoTpScaRFTlcJtbx+8/Wv5WQWMfW",
	"344WYdFRo3hHhsJ3ub4ikd/V1k1aj6MtVp3n02rbuW9JqoWrtX6b6Wdl8RfkV0Uq2MMuK070Veeyktbj",
	"bSv+14Rf1y5TXwRJ022lciYg5TV/fZ3h5rr0T4tXNZ4sPLMEyIy1pICylnETeTCS6zCFmphLx5lGIJbI",
	"pSI5g/6W7UWTkh0qQtJDVmRHoCmTRw52Pd8PrPnLGFpIhWKFyA/k/eGdUJOKHopC73b0t2abfxf8lw+e",
	"bQ+9sLXqfAbwtQWZAEhESkCqKFBafPoCGeG9iCjwdxNRzfDxen779uC3Ir+DEnX+iIoEGQJ6pruRjTYK",
	"2vV2Y0QhW2E1ildHwrUFIcgY6MMh0w0zVZJht3NpfiApMnOM/9H2UR9HqI5fNRGGykU4kIm8dq5VmhKq",
	"qVZlBQPndu+zf+yL9tyX6DeRf9T8EKYqTYc5S0fEJujY5hi5JrAx94RYwaErYc/GHX8kcjXgjEaWmokB",
	"Xz/u3Mb5G6QmQjYEC4lKSKDUNCFVbEN2q7FLRzxMYa4ZI/RJqAlKGxFlOvzqXNHTnkuPzgU0apVzvVIv",
	"WdivaAOMZ0H1gegFTQn7mAqpUEZyoh8Ka4lA8zHgL7+7lQjxblai6+S+ozSnhoIfTJTOTqL8O+RQCvZV",
	"/VLneTOTpv2AnjzeSWpNAPeNhCYkErlJZREFRioJxmEIQ4Tx9nmRH8BMa2CudKYrp5Cr7+/7d3vVi0j3",
	"28n1awaZexKiu5MQLwp1VlQ5/0YRO3CdJxZVyaD/thNDxPd/195O0rus1A/wsIuaisGX3cz//mq5m2DH",
	"s7MmNvxmktWKKHIdgUOuo/k6vhuhTEipw0ljPhswU35/TQ12yyVXgIefNrMjy61joDOAV1lR5bVici7q",
	"/OmqI5OEpBJWwMOHwRrMRZVRKHWiUU/YBqIbWZKoQk7EwH41bVqNb9o5W6J+3XxFLtbWZA1J4lcgqRrA",
	"Qifm7w8Nfr6CAjbDq+s+NeD8yvr5rTaCXYbWNe1EDuH9MJumROTSGMlpgwCaVC4DRbKinPbx2rxAnOqU",
	"JwfWJHZPpI9DcGknzdikH/NjP1sZmTVmRfwF02a5bxBjU91SMynuiqlk+nJlO8HDsRcHIY79+aTFaqdB",
	"nEdWJnKR3zVQUqOGjhlZqJGjGenf0yBNywJ+S2Yiq7K2wqOnovfmjNstVXktd+uOyucvRoq7nKiqBKTp",
	"Npm43O3Upxnr1QafwV1X9pts7MKsLL/FoXtYL7ZV1rpE3K7V1i64v51XWCoKaMewgzlcyH3TGS0qvSSS",
	"ZvEqN7ePo67vabD+Pk+dZ9cp6FjWUmXF7sF1eriu4F8RbfNMZUff+KKkYWEbuwe2e2DHYwcf2+6xFx26",
	"EY4d23e8/9GTZ23pz1oqmFkt0GUxmwcJg9DxwMPYDxwvsW2bBcQnnBNCHNdzCKM0ZlHoOL7jeJwlkZe4",
	"IY09n5jIoi/pDaDj6QassaP4fVx0NWaq48stkLauBDdBem+bXgmiJnWLxwRmqN5Ge7bX795eNcEZev/6",
	"+uQg9G7npRpaskMO90eh93Ir8G+2rhw7XukK0HLIq0xr4LuLf1xc/nFhjay27GqNrLrmao2soYKrmbpa",
	"bdXL+qVW85dl7Xh7fmF2Prm8ODu/fmt+vj79j9OT8ekb/Q4W99PWaK1BZrcAU0Wuxd2784ByyhJCbR8H",
	"3LUh4kGEwzgJY54kgZNQz8YBYRDRkLo4jGKS2E7gugH4XoIT29rCbd6ONpDFm4e8hKpqdoZMWmdppxzV",
	"efgl+TSeWcfWn5Vtu6xr4xeaZsZg9T01a5eleE0+dRY/iQjXuzxJ/B6M8sbp8zr4UzMHrOqOFn8rO/QN",
	"rcj3NCNf+DKfKDbMjDWek9R1ZE+6zOtux8U30LkdFKjzTM3vQkFmftiu+r5Gg59MfGsRNVIjZUkeBs1X",
	"X4wLbfixZLiXYOD/g5+f+77W8+7NmYYxDrHrcsfmhHE/sAMG4NPEpjgKgihhTuxA6No2jgkDj4UJ82zg",
	"4McER9iH7d7/0EN/HFmyaZK60YpUq8RrICWUr6qhy6rHEKnUBHLVNqz2W2auz05QEPp228xlUnOzbkGp",
	"vrS6o0s0upcKBo1na3rDLqeQo9c3v6Pf9BDTfFZlugrlECkLJgwlhzmoo2IK+QGV9wfNlkfmcoQywtb7",
	"vbo+sUbWPZSyZso5tA9tPUmvJFNhHVuu+dPI0ppohHJ07xxN5vjGHaihRjFgHyUSyQJL0AFxi16QnKOy",
	"yvM6GJgnqOc6yP/76bgBT5Za3LBtm7bpIlfQIEzTadrI/eifDcax6JnbZCOaE4zUlzrlKtN3rUXg2c66",
	"feaEHfUb74waVVlGygfNCqgO/5OWK0XupNbFVyWzjOJpgS5yvkGBjk0Vv+mBbrobG+SmrppKUErkd/Jw",
	"SKBXbbb71QS6lCh/A8EO8L5OtmpWZ9XyScEKWffOqwJJ05yOStLvgVYFInVziWk/Nd0t0uR7dS9MDjNV",
	"d7kgNSFq0YuCWAlEgTxEaDyBthV/8UkAYiSf9+6rwvTdloLXNYy7tKAknTOqD3soqhK9KhniRE5oQUre",
	"9vXLnk8a0Iiry5vxuOe1ul8mrPHGiylH3Sb/dd64M321236LRZ229S1mrzaHb7lopY16y3W91uYt1vQ/",
	"9thiQb8fWmeATY3wdcEf9vZsB5JB/Wi6GxZMgTqQqgSS9TeeY3xU5PpdDiayMFNHBmfur124/C3SzNWN",
	"HzclxL1Mc+H8dfDz+CwT2BBbB4ltJ+3CGp03Rcem0Kj9KUkr6NZ/9lWn7ONupGRNZ5cXuMdo6deuSOu9",
	"kY1aVLtDhNUtL+lYcY63EZsHMcE8ITx07DC0geMIMwauEzA/jHESOLZDgsj2AoIDlzghcQjYOAgD2+lG",
	"YztX6f+06o9XIJsWRdqXd0+WOWrndMT+Bdjlj4lb1mh53csxLIh6eI0Mem32hLAoTihwJ3CBB7YdOJS4",
	"LmU2oTGHCMKER9T1CI89hj3HY3xZhqEbYBxtFmQCvod9J7JtG9ue/n/E4zCJgQLnPE5iQiKwIfZd6pIw",
	"SFwnwHFEqO1DHLkeIZHjhE4AMXfj0A888G3Hxn4SeGahgwEHxGd+ZLssTmKPOwyzCEgQAYPE8Rzfdhxw",
	"mJ5HYxYHAQ0It7GNncRPiBsHdsiIS72I+y6LbUy5T6lHaRKQkLA4ZkmccOL5jGGHhg4EgJMwiuLAdm3s",
	"EUyp4wQQBS72WUwj38GJY1OMGcYRoS4OcQJu4oYudSj3SEwC6roetYOI0sDG+ioCJ4xdisPItV39khw3",
	"thkQ8EnouBxsIJTHjJPADW2cQOSxGEdxaBOWhMzzwXZsm/hBCC63gwDcKHAjvV0c+n7s2hgIZZEPNIgp",
	"tjHDEAXcc92IEqqTqCjxgi8B6ufpX63mNIioHXjUdQMaE49QTp3QTVxwcYJD6kYEY8wodmyc+A6NWIz9",
	"wIXICaiDqUdqu/4Mx7Vl0Lm/aHe5n3/g5NeEt109zw159ap4vzS3/YkDBDdDTbe3Phzj/R4+dOq7vOlz",
	"IDQFpPNo9YAO6jJ0/3uTulF6AQVr1d0refOmmgEyLwq13PpS0+Dsl4bVD2BWaZk39vWQJ0PNni+s/bBm",
	"lYY25BHtpzeWF7j7Pbzzpc5OMvD2S0bbw7ZBCG3cZ47393v8GQzatTPofJPSS41vKpoJhUhXMIfrE+Oj",
	"z9p4P26JO3TS47smBWdVWeogtfk0s0gQQdMS7kVRyfQBSUOO6l/UIEaxChCvpKXLpPW/PDl/g1642LQK",
	"mY8NX/YTAfPN5ZQYBKZB1ZpiQD9F2PTl+O1XRFBW+d8/iKJX7fl9zDtk11jNeefqd/Rlq9jRCqy94YnI",
	"54JHWZUqMU1hGUOS+wCRfjAMSf4Ekf6lQaR5PXFXNGmgOvhjoUt/5s9DoL4cSiKcb8roh6CN9/+C2Mbt",
	"42gnVO39T1jt2bBaLe3doKT3XxlLCpwo+Ikl/cSS9owl3X4RmCSfKjI03RA/gaVnAEs/kZufyM1P5GYN",
	"cjPPGpfzr6X0tNOwZHx0t1Xp/a1ODl5NxcE/4GH+a/efAjR/vNVblPdtwtbvKFJkKhZflZGSaZP6fwEA",
	"AP//hCLB3NJQAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
