// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/api/grpc_api/grpc_api.proto

package grpc_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// swagger:model HealthResponse
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_api_grpc_api_grpc_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_api_grpc_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_api_grpc_api_proto_rawDescGZIP(), []int{0}
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_internal_api_grpc_api_grpc_api_proto protoreflect.FileDescriptor

const file_internal_api_grpc_api_grpc_api_proto_rawDesc = "" +
	"\n" +
	"$internal/api/grpc_api/grpc_api.proto\x12\bgrpc_api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"J\n" +
	"\x0eHealthResponse\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2G\n" +
	"\aGrpcAPI\x12<\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a\x18.grpc_api.HealthResponse\"\x00B\fZ\n" +
	".;grpc_apib\x06proto3"

var (
	file_internal_api_grpc_api_grpc_api_proto_rawDescOnce sync.Once
	file_internal_api_grpc_api_grpc_api_proto_rawDescData []byte
)

func file_internal_api_grpc_api_grpc_api_proto_rawDescGZIP() []byte {
	file_internal_api_grpc_api_grpc_api_proto_rawDescOnce.Do(func() {
		file_internal_api_grpc_api_grpc_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_grpc_api_grpc_api_proto_rawDesc), len(file_internal_api_grpc_api_grpc_api_proto_rawDesc)))
	})
	return file_internal_api_grpc_api_grpc_api_proto_rawDescData
}

var file_internal_api_grpc_api_grpc_api_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_api_grpc_api_grpc_api_proto_goTypes = []any{
	(*HealthResponse)(nil),        // 0: grpc_api.HealthResponse
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 2: google.protobuf.Empty
}
var file_internal_api_grpc_api_grpc_api_proto_depIdxs = []int32{
	1, // 0: grpc_api.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: grpc_api.GrpcAPI.Health:input_type -> google.protobuf.Empty
	0, // 2: grpc_api.GrpcAPI.Health:output_type -> grpc_api.HealthResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_api_grpc_api_grpc_api_proto_init() }
func file_internal_api_grpc_api_grpc_api_proto_init() {
	if File_internal_api_grpc_api_grpc_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_grpc_api_grpc_api_proto_rawDesc), len(file_internal_api_grpc_api_grpc_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_grpc_api_grpc_api_proto_goTypes,
		DependencyIndexes: file_internal_api_grpc_api_grpc_api_proto_depIdxs,
		MessageInfos:      file_internal_api_grpc_api_grpc_api_proto_msgTypes,
	}.Build()
	File_internal_api_grpc_api_grpc_api_proto = out.File
	file_internal_api_grpc_api_grpc_api_proto_goTypes = nil
	file_internal_api_grpc_api_grpc_api_proto_depIdxs = nil
}
