@startuml
title Transaction lifecycle

state VALIDATED
state ANNOUNCED
state ERROR
state REQUESTED_BY_NETWORK
state SENT_TO_NETWORK
state SEEN_ON_NETWORK
state REJECTED
state MINED

[*] --> VALIDATED

VALIDATED --> ANNOUNCED
note on link
  Transaction has passed all checks except
  for verifying each UTXO is correct. This
  check is done by the nodes themselves.
end note
VALIDATED -> ERROR: Bad transaction

ANNOUNCED --> REQUESTED_BY_NETWORK
note on link
  Transaction ID has been announced to P2P
  network via an INV message.
end note

REQUESTED_BY_NETWORK --> SENT_TO_NETWORK
note on link
  Peer has requested the transaction with a
  GETDATA message.
end note


SENT_TO_NETWORK -> REJECTED
note on link
  Peer has sent a REJECT message.
end note

SENT_TO_NETWORK --> SEEN_ON_NETWORK
note on link
  Transaction has been sent to peer.
end note


SEEN_ON_NETWORK --> MINED
note on link
  Transaction ID has been announced to us
  from another peer.
end note


MINED --> [*]
note on link
  Transaction ID was included in a BLOCK message.
end note


@enduml
