ALTER TABLE transactions
ADD COLUMN  inserted_at TIMESTAMP WITH TIME ZONE  DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE block_transactions_map
ADD COLUMN  inserted_at TIMESTAMP WITH TIME ZONE  DEFAULT CURRENT_TIMESTAMP NOT NULL;
