// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package blocktx

import (
	"github.com/bitcoin-sv/arc/pkg/blocktx/blocktx_api"
	"sync"
)

// Ensure, that MessageQueueClientMock does implement MessageQueueClient.
// If this is not the case, regenerate this file with moq.
var _ MessageQueueClient = &MessageQueueClientMock{}

// MessageQueueClientMock is a mock implementation of MessageQueueClient.
//
//	func TestSomethingThatUsesMessageQueueClient(t *testing.T) {
//
//		// make and configure a mocked MessageQueueClient
//		mockedMessageQueueClient := &MessageQueueClientMock{
//			PublishMinedTxsFunc: func(txsBlocks []*blocktx_api.TransactionBlock) error {
//				panic("mock out the PublishMinedTxs method")
//			},
//			ShutdownFunc: func() error {
//				panic("mock out the Shutdown method")
//			},
//			SubscribeRegisterTxsFunc: func() error {
//				panic("mock out the SubscribeRegisterTxs method")
//			},
//		}
//
//		// use mockedMessageQueueClient in code that requires MessageQueueClient
//		// and then make assertions.
//
//	}
type MessageQueueClientMock struct {
	// PublishMinedTxsFunc mocks the PublishMinedTxs method.
	PublishMinedTxsFunc func(txsBlocks []*blocktx_api.TransactionBlock) error

	// ShutdownFunc mocks the Shutdown method.
	ShutdownFunc func() error

	// SubscribeRegisterTxsFunc mocks the SubscribeRegisterTxs method.
	SubscribeRegisterTxsFunc func() error

	// calls tracks calls to the methods.
	calls struct {
		// PublishMinedTxs holds details about calls to the PublishMinedTxs method.
		PublishMinedTxs []struct {
			// TxsBlocks is the txsBlocks argument value.
			TxsBlocks []*blocktx_api.TransactionBlock
		}
		// Shutdown holds details about calls to the Shutdown method.
		Shutdown []struct {
		}
		// SubscribeRegisterTxs holds details about calls to the SubscribeRegisterTxs method.
		SubscribeRegisterTxs []struct {
		}
	}
	lockPublishMinedTxs      sync.RWMutex
	lockShutdown             sync.RWMutex
	lockSubscribeRegisterTxs sync.RWMutex
}

// PublishMinedTxs calls PublishMinedTxsFunc.
func (mock *MessageQueueClientMock) PublishMinedTxs(txsBlocks []*blocktx_api.TransactionBlock) error {
	if mock.PublishMinedTxsFunc == nil {
		panic("MessageQueueClientMock.PublishMinedTxsFunc: method is nil but MessageQueueClient.PublishMinedTxs was just called")
	}
	callInfo := struct {
		TxsBlocks []*blocktx_api.TransactionBlock
	}{
		TxsBlocks: txsBlocks,
	}
	mock.lockPublishMinedTxs.Lock()
	mock.calls.PublishMinedTxs = append(mock.calls.PublishMinedTxs, callInfo)
	mock.lockPublishMinedTxs.Unlock()
	return mock.PublishMinedTxsFunc(txsBlocks)
}

// PublishMinedTxsCalls gets all the calls that were made to PublishMinedTxs.
// Check the length with:
//
//	len(mockedMessageQueueClient.PublishMinedTxsCalls())
func (mock *MessageQueueClientMock) PublishMinedTxsCalls() []struct {
	TxsBlocks []*blocktx_api.TransactionBlock
} {
	var calls []struct {
		TxsBlocks []*blocktx_api.TransactionBlock
	}
	mock.lockPublishMinedTxs.RLock()
	calls = mock.calls.PublishMinedTxs
	mock.lockPublishMinedTxs.RUnlock()
	return calls
}

// Shutdown calls ShutdownFunc.
func (mock *MessageQueueClientMock) Shutdown() error {
	if mock.ShutdownFunc == nil {
		panic("MessageQueueClientMock.ShutdownFunc: method is nil but MessageQueueClient.Shutdown was just called")
	}
	callInfo := struct {
	}{}
	mock.lockShutdown.Lock()
	mock.calls.Shutdown = append(mock.calls.Shutdown, callInfo)
	mock.lockShutdown.Unlock()
	return mock.ShutdownFunc()
}

// ShutdownCalls gets all the calls that were made to Shutdown.
// Check the length with:
//
//	len(mockedMessageQueueClient.ShutdownCalls())
func (mock *MessageQueueClientMock) ShutdownCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockShutdown.RLock()
	calls = mock.calls.Shutdown
	mock.lockShutdown.RUnlock()
	return calls
}

// SubscribeRegisterTxs calls SubscribeRegisterTxsFunc.
func (mock *MessageQueueClientMock) SubscribeRegisterTxs() error {
	if mock.SubscribeRegisterTxsFunc == nil {
		panic("MessageQueueClientMock.SubscribeRegisterTxsFunc: method is nil but MessageQueueClient.SubscribeRegisterTxs was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSubscribeRegisterTxs.Lock()
	mock.calls.SubscribeRegisterTxs = append(mock.calls.SubscribeRegisterTxs, callInfo)
	mock.lockSubscribeRegisterTxs.Unlock()
	return mock.SubscribeRegisterTxsFunc()
}

// SubscribeRegisterTxsCalls gets all the calls that were made to SubscribeRegisterTxs.
// Check the length with:
//
//	len(mockedMessageQueueClient.SubscribeRegisterTxsCalls())
func (mock *MessageQueueClientMock) SubscribeRegisterTxsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSubscribeRegisterTxs.RLock()
	calls = mock.calls.SubscribeRegisterTxs
	mock.lockSubscribeRegisterTxs.RUnlock()
	return calls
}
