// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	Api_KeyScopes       = "Api_Key.Scopes"
	AuthorizationScopes = "Authorization.Scopes"
	BearerAuthScopes    = "BearerAuth.Scopes"
)

// Defines values for TransactionDetailsTxStatus.
const (
	ANNOUNCEDTONETWORK TransactionDetailsTxStatus = "ANNOUNCED_TO_NETWORK"
	CONFIRMED          TransactionDetailsTxStatus = "CONFIRMED"
	MINED              TransactionDetailsTxStatus = "MINED"
	RECEIVED           TransactionDetailsTxStatus = "RECEIVED"
	REJECTED           TransactionDetailsTxStatus = "REJECTED"
	REQUESTEDBYNETWORK TransactionDetailsTxStatus = "REQUESTED_BY_NETWORK"
	SEENONNETWORK      TransactionDetailsTxStatus = "SEEN_ON_NETWORK"
	SENTTONETWORK      TransactionDetailsTxStatus = "SENT_TO_NETWORK"
	STORED             TransactionDetailsTxStatus = "STORED"
	UNKNOWN            TransactionDetailsTxStatus = "UNKNOWN"
)

// ChainInfo Chain info
type ChainInfo struct {
	// BlockHash Block hash
	BlockHash *string `json:"blockHash,omitempty"`

	// BlockHeight Block height
	BlockHeight *uint64 `json:"blockHeight,omitempty"`
}

// CommonResponse Common response object
type CommonResponse struct {
	Timestamp time.Time `json:"timestamp"`
}

// Error An HTTP Problem Details object, as defined in IETF RFC 7807 (https://tools.ietf.org/html/rfc7807).
type Error struct {
	union json.RawMessage
}

// ErrorBadRequest defines model for ErrorBadRequest.
type ErrorBadRequest struct {
	Detail interface{} `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`
	Status    interface{}  `json:"status"`
	Title     interface{}  `json:"title"`

	// Txid Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorConflict defines model for ErrorConflict.
type ErrorConflict struct {
	Detail interface{} `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`
	Status    interface{}  `json:"status"`
	Title     interface{}  `json:"title"`

	// Txid Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorFee defines model for ErrorFee.
type ErrorFee struct {
	Detail interface{} `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`
	Status    interface{}  `json:"status"`
	Title     interface{}  `json:"title"`

	// Txid Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorFields defines model for ErrorFields.
type ErrorFields struct {
	// Detail Longer description of error
	Detail string `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string `json:"extraInfo"`

	// Instance (Optional) Link to actual error on server
	Instance *string `json:"instance"`

	// Status Error code
	Status int `json:"status"`

	// Title Descriptive text for error
	Title string `json:"title"`

	// Txid Transaction ID this error is referring to
	Txid *string `json:"txid"`

	// Type Type of error, with link to more information
	Type string `json:"type"`
}

// ErrorFrozenConsensus defines model for ErrorFrozenConsensus.
type ErrorFrozenConsensus struct {
	Detail interface{} `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`
	Status    interface{}  `json:"status"`
	Title     interface{}  `json:"title"`

	// Txid Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorFrozenPolicy defines model for ErrorFrozenPolicy.
type ErrorFrozenPolicy struct {
	Detail interface{} `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`
	Status    interface{}  `json:"status"`
	Title     interface{}  `json:"title"`

	// Txid Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorInputs defines model for ErrorInputs.
type ErrorInputs struct {
	Detail interface{} `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`
	Status    interface{}  `json:"status"`
	Title     interface{}  `json:"title"`

	// Txid Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorMalformed defines model for ErrorMalformed.
type ErrorMalformed struct {
	Detail interface{} `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`
	Status    interface{}  `json:"status"`
	Title     interface{}  `json:"title"`

	// Txid Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// ErrorUnlockingScripts defines model for ErrorUnlockingScripts.
type ErrorUnlockingScripts struct {
	Detail interface{} `json:"detail"`

	// ExtraInfo Optional extra information about the error from the miner
	ExtraInfo *string      `json:"extraInfo"`
	Instance  *interface{} `json:"instance,omitempty"`
	Status    interface{}  `json:"status"`
	Title     interface{}  `json:"title"`

	// Txid Transaction ID this error is referring to
	Txid *string     `json:"txid"`
	Type interface{} `json:"type"`
}

// FeeAmount defines model for FeeAmount.
type FeeAmount struct {
	// Bytes Number of bytes
	Bytes uint64 `json:"bytes"`

	// Satoshis Amount in Satoshis
	Satoshis uint64 `json:"satoshis"`
}

// Policy defines model for Policy.
type Policy struct {
	// Maxscriptsizepolicy Maximum script size [bytes]
	Maxscriptsizepolicy uint64 `json:"maxscriptsizepolicy"`

	// Maxtxsigopscountspolicy Maximum number of signature operations
	Maxtxsigopscountspolicy uint64 `json:"maxtxsigopscountspolicy"`

	// Maxtxsizepolicy Maximum transaction size [bytes]
	Maxtxsizepolicy uint64    `json:"maxtxsizepolicy"`
	MiningFee       FeeAmount `json:"miningFee"`
}

// PolicyResponse defines model for PolicyResponse.
type PolicyResponse struct {
	Policy    Policy    `json:"policy"`
	Timestamp time.Time `json:"timestamp"`
}

// TransactionDetails defines model for TransactionDetails.
type TransactionDetails struct {
	// ExtraInfo Extra information about the transaction
	ExtraInfo *string `json:"extraInfo"`

	// MerklePath Transaction merkle path in hex
	MerklePath *string `json:"merklePath"`

	// Status Status
	Status int `json:"status"`

	// Title Title
	Title string `json:"title"`

	// TxStatus Transaction status
	TxStatus *TransactionDetailsTxStatus `json:"txStatus,omitempty"`

	// Txid Transaction ID in hex
	Txid *string `json:"txid,omitempty"`
}

// TransactionDetailsTxStatus Transaction status
type TransactionDetailsTxStatus string

// TransactionRequest defines model for TransactionRequest.
type TransactionRequest struct {
	// RawTx Raw hex string
	RawTx string `json:"rawTx"`
}

// TransactionResponse defines model for TransactionResponse.
type TransactionResponse struct {
	// BlockHash Block hash
	BlockHash *string `json:"blockHash,omitempty"`

	// BlockHeight Block height
	BlockHeight *uint64 `json:"blockHeight,omitempty"`

	// ExtraInfo Extra info
	ExtraInfo *string `json:"extraInfo"`

	// MerklePath Transaction merkle path in hex
	MerklePath *string `json:"merklePath"`

	// Status Status
	Status    int       `json:"status"`
	Timestamp time.Time `json:"timestamp"`

	// Title Title
	Title string `json:"title"`

	// TxStatus Transaction status
	TxStatus string `json:"txStatus"`

	// Txid Transaction ID in hex
	Txid string `json:"txid"`
}

// TransactionResponses defines model for TransactionResponses.
type TransactionResponses struct {
	// BlockHash Block hash
	BlockHash *string `json:"blockHash,omitempty"`

	// BlockHeight Block height
	BlockHeight  *uint64                                   `json:"blockHeight,omitempty"`
	Timestamp    time.Time                                 `json:"timestamp"`
	Transactions *[]TransactionResponses_Transactions_Item `json:"transactions,omitempty"`
}

// TransactionResponses_Transactions_Item defines model for TransactionResponses.transactions.Item.
type TransactionResponses_Transactions_Item struct {
	union json.RawMessage
}

// TransactionStatus defines model for TransactionStatus.
type TransactionStatus struct {
	// BlockHash Block hash
	BlockHash *string `json:"blockHash,omitempty"`

	// BlockHeight Block height
	BlockHeight *uint64 `json:"blockHeight,omitempty"`

	// ExtraInfo Extra information about the transaction
	ExtraInfo *string `json:"extraInfo"`

	// MerklePath Transaction merkle path in hex
	MerklePath *string   `json:"merklePath"`
	Timestamp  time.Time `json:"timestamp"`

	// TxStatus Transaction status
	TxStatus *string `json:"txStatus,omitempty"`

	// Txid Transaction ID in hex
	Txid string `json:"txid"`
}

// TransactionSubmitStatus Transaction submit status
type TransactionSubmitStatus struct {
	// Status Status
	Status int `json:"status"`

	// Title Title
	Title string `json:"title"`
}

// CallbackToken defines model for callbackToken.
type CallbackToken = string

// CallbackUrl defines model for callbackUrl.
type CallbackUrl = string

// MerkleProof defines model for merkleProof.
type MerkleProof = string

// SkipFeeValidation defines model for skipFeeValidation.
type SkipFeeValidation = bool

// SkipScriptValidation defines model for skipScriptValidation.
type SkipScriptValidation = bool

// WaitForStatus defines model for waitForStatus.
type WaitForStatus = int

// POSTTransactionTextBody defines parameters for POSTTransaction.
type POSTTransactionTextBody = string

// POSTTransactionParams defines parameters for POSTTransaction.
type POSTTransactionParams struct {
	// XCallbackUrl Default double spend and merkle proof notification callback endpoint.
	XCallbackUrl *CallbackUrl `json:"X-CallbackUrl,omitempty"`

	// XSkipFeeValidation Wheather we should skip fee validation or not.
	XSkipFeeValidation *SkipFeeValidation `json:"X-SkipFeeValidation,omitempty"`

	// XSkipScriptValidation Wheather we should skip script validation or not.
	XSkipScriptValidation *SkipScriptValidation `json:"X-SkipScriptValidation,omitempty"`

	// XCallbackToken Access token for notification callback endpoint.
	XCallbackToken *CallbackToken `json:"X-CallbackToken,omitempty"`

	// XMerkleProof Whether to include merkle proofs in the callbacks (true | false).
	XMerkleProof *MerkleProof `json:"X-MerkleProof,omitempty"`

	// XWaitForStatus Which status to wait for from the server before returning (2 = RECEIVED, 3 = STORED, 4 = ANNOUNCED_TO_NETWORK, 5 = REQUESTED_BY_NETWORK, 6 = SENT_TO_NETWORK, 7 = ACCEPTED_BY_NETWORK, 8 = SEEN_ON_NETWORK)
	XWaitForStatus *WaitForStatus `json:"X-WaitForStatus,omitempty"`
}

// POSTTransactionsJSONBody defines parameters for POSTTransactions.
type POSTTransactionsJSONBody = []TransactionRequest

// POSTTransactionsTextBody defines parameters for POSTTransactions.
type POSTTransactionsTextBody = string

// POSTTransactionsParams defines parameters for POSTTransactions.
type POSTTransactionsParams struct {
	// XCallbackUrl Default double spend and merkle proof notification callback endpoint.
	XCallbackUrl *CallbackUrl `json:"X-CallbackUrl,omitempty"`

	// XSkipFeeValidation Wheather we should skip fee validation or not.
	XSkipFeeValidation *SkipFeeValidation `json:"X-SkipFeeValidation,omitempty"`

	// XSkipScriptValidation Wheather we should skip script validation or not.
	XSkipScriptValidation *SkipScriptValidation `json:"X-SkipScriptValidation,omitempty"`

	// XCallbackToken Access token for notification callback endpoint.
	XCallbackToken *CallbackToken `json:"X-CallbackToken,omitempty"`

	// XMerkleProof Whether to include merkle proofs in the callbacks (true | false).
	XMerkleProof *MerkleProof `json:"X-MerkleProof,omitempty"`

	// XWaitForStatus Which status to wait for from the server before returning (2 = RECEIVED, 3 = STORED, 4 = ANNOUNCED_TO_NETWORK, 5 = REQUESTED_BY_NETWORK, 6 = SENT_TO_NETWORK, 7 = ACCEPTED_BY_NETWORK, 8 = SEEN_ON_NETWORK)
	XWaitForStatus *WaitForStatus `json:"X-WaitForStatus,omitempty"`
}

// POSTTransactionJSONRequestBody defines body for POSTTransaction for application/json ContentType.
type POSTTransactionJSONRequestBody = TransactionRequest

// POSTTransactionTextRequestBody defines body for POSTTransaction for text/plain ContentType.
type POSTTransactionTextRequestBody = POSTTransactionTextBody

// POSTTransactionsJSONRequestBody defines body for POSTTransactions for application/json ContentType.
type POSTTransactionsJSONRequestBody = POSTTransactionsJSONBody

// POSTTransactionsTextRequestBody defines body for POSTTransactions for text/plain ContentType.
type POSTTransactionsTextRequestBody = POSTTransactionsTextBody

// AsErrorUnlockingScripts returns the union data inside the Error as a ErrorUnlockingScripts
func (t Error) AsErrorUnlockingScripts() (ErrorUnlockingScripts, error) {
	var body ErrorUnlockingScripts
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorUnlockingScripts overwrites any union data inside the Error as the provided ErrorUnlockingScripts
func (t *Error) FromErrorUnlockingScripts(v ErrorUnlockingScripts) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorUnlockingScripts performs a merge with any union data inside the Error, using the provided ErrorUnlockingScripts
func (t *Error) MergeErrorUnlockingScripts(v ErrorUnlockingScripts) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorInputs returns the union data inside the Error as a ErrorInputs
func (t Error) AsErrorInputs() (ErrorInputs, error) {
	var body ErrorInputs
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorInputs overwrites any union data inside the Error as the provided ErrorInputs
func (t *Error) FromErrorInputs(v ErrorInputs) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorInputs performs a merge with any union data inside the Error, using the provided ErrorInputs
func (t *Error) MergeErrorInputs(v ErrorInputs) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorMalformed returns the union data inside the Error as a ErrorMalformed
func (t Error) AsErrorMalformed() (ErrorMalformed, error) {
	var body ErrorMalformed
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorMalformed overwrites any union data inside the Error as the provided ErrorMalformed
func (t *Error) FromErrorMalformed(v ErrorMalformed) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorMalformed performs a merge with any union data inside the Error, using the provided ErrorMalformed
func (t *Error) MergeErrorMalformed(v ErrorMalformed) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorFrozenPolicy returns the union data inside the Error as a ErrorFrozenPolicy
func (t Error) AsErrorFrozenPolicy() (ErrorFrozenPolicy, error) {
	var body ErrorFrozenPolicy
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorFrozenPolicy overwrites any union data inside the Error as the provided ErrorFrozenPolicy
func (t *Error) FromErrorFrozenPolicy(v ErrorFrozenPolicy) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorFrozenPolicy performs a merge with any union data inside the Error, using the provided ErrorFrozenPolicy
func (t *Error) MergeErrorFrozenPolicy(v ErrorFrozenPolicy) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorFrozenConsensus returns the union data inside the Error as a ErrorFrozenConsensus
func (t Error) AsErrorFrozenConsensus() (ErrorFrozenConsensus, error) {
	var body ErrorFrozenConsensus
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorFrozenConsensus overwrites any union data inside the Error as the provided ErrorFrozenConsensus
func (t *Error) FromErrorFrozenConsensus(v ErrorFrozenConsensus) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorFrozenConsensus performs a merge with any union data inside the Error, using the provided ErrorFrozenConsensus
func (t *Error) MergeErrorFrozenConsensus(v ErrorFrozenConsensus) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t Error) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Error) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsTransactionDetails returns the union data inside the TransactionResponses_Transactions_Item as a TransactionDetails
func (t TransactionResponses_Transactions_Item) AsTransactionDetails() (TransactionDetails, error) {
	var body TransactionDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTransactionDetails overwrites any union data inside the TransactionResponses_Transactions_Item as the provided TransactionDetails
func (t *TransactionResponses_Transactions_Item) FromTransactionDetails(v TransactionDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTransactionDetails performs a merge with any union data inside the TransactionResponses_Transactions_Item, using the provided TransactionDetails
func (t *TransactionResponses_Transactions_Item) MergeTransactionDetails(v TransactionDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsError returns the union data inside the TransactionResponses_Transactions_Item as a Error
func (t TransactionResponses_Transactions_Item) AsError() (Error, error) {
	var body Error
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromError overwrites any union data inside the TransactionResponses_Transactions_Item as the provided Error
func (t *TransactionResponses_Transactions_Item) FromError(v Error) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeError performs a merge with any union data inside the TransactionResponses_Transactions_Item, using the provided Error
func (t *TransactionResponses_Transactions_Item) MergeError(v Error) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t TransactionResponses_Transactions_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TransactionResponses_Transactions_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GETPolicy request
	GETPolicy(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// POSTTransactionWithBody request with any body
	POSTTransactionWithBody(ctx context.Context, params *POSTTransactionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	POSTTransaction(ctx context.Context, params *POSTTransactionParams, body POSTTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	POSTTransactionWithTextBody(ctx context.Context, params *POSTTransactionParams, body POSTTransactionTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GETTransactionStatus request
	GETTransactionStatus(ctx context.Context, txid string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// POSTTransactionsWithBody request with any body
	POSTTransactionsWithBody(ctx context.Context, params *POSTTransactionsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	POSTTransactions(ctx context.Context, params *POSTTransactionsParams, body POSTTransactionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	POSTTransactionsWithTextBody(ctx context.Context, params *POSTTransactionsParams, body POSTTransactionsTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GETPolicy(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGETPolicyRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) POSTTransactionWithBody(ctx context.Context, params *POSTTransactionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPOSTTransactionRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) POSTTransaction(ctx context.Context, params *POSTTransactionParams, body POSTTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPOSTTransactionRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) POSTTransactionWithTextBody(ctx context.Context, params *POSTTransactionParams, body POSTTransactionTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPOSTTransactionRequestWithTextBody(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GETTransactionStatus(ctx context.Context, txid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGETTransactionStatusRequest(c.Server, txid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) POSTTransactionsWithBody(ctx context.Context, params *POSTTransactionsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPOSTTransactionsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) POSTTransactions(ctx context.Context, params *POSTTransactionsParams, body POSTTransactionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPOSTTransactionsRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) POSTTransactionsWithTextBody(ctx context.Context, params *POSTTransactionsParams, body POSTTransactionsTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPOSTTransactionsRequestWithTextBody(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGETPolicyRequest generates requests for GETPolicy
func NewGETPolicyRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/policy")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPOSTTransactionRequest calls the generic POSTTransaction builder with application/json body
func NewPOSTTransactionRequest(server string, params *POSTTransactionParams, body POSTTransactionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPOSTTransactionRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPOSTTransactionRequestWithTextBody calls the generic POSTTransaction builder with text/plain body
func NewPOSTTransactionRequestWithTextBody(server string, params *POSTTransactionParams, body POSTTransactionTextRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyReader = strings.NewReader(string(body))
	return NewPOSTTransactionRequestWithBody(server, params, "text/plain", bodyReader)
}

// NewPOSTTransactionRequestWithBody generates requests for POSTTransaction with any type of body
func NewPOSTTransactionRequestWithBody(server string, params *POSTTransactionParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/tx")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XCallbackUrl != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-CallbackUrl", runtime.ParamLocationHeader, *params.XCallbackUrl)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-CallbackUrl", headerParam0)
		}

		if params.XSkipFeeValidation != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithLocation("simple", false, "X-SkipFeeValidation", runtime.ParamLocationHeader, *params.XSkipFeeValidation)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-SkipFeeValidation", headerParam1)
		}

		if params.XSkipScriptValidation != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithLocation("simple", false, "X-SkipScriptValidation", runtime.ParamLocationHeader, *params.XSkipScriptValidation)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-SkipScriptValidation", headerParam2)
		}

		if params.XCallbackToken != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithLocation("simple", false, "X-CallbackToken", runtime.ParamLocationHeader, *params.XCallbackToken)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-CallbackToken", headerParam3)
		}

		if params.XMerkleProof != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithLocation("simple", false, "X-MerkleProof", runtime.ParamLocationHeader, *params.XMerkleProof)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-MerkleProof", headerParam4)
		}

		if params.XWaitForStatus != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithLocation("simple", false, "X-WaitForStatus", runtime.ParamLocationHeader, *params.XWaitForStatus)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-WaitForStatus", headerParam5)
		}

	}

	return req, nil
}

// NewGETTransactionStatusRequest generates requests for GETTransactionStatus
func NewGETTransactionStatusRequest(server string, txid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "txid", runtime.ParamLocationPath, txid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/tx/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPOSTTransactionsRequest calls the generic POSTTransactions builder with application/json body
func NewPOSTTransactionsRequest(server string, params *POSTTransactionsParams, body POSTTransactionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPOSTTransactionsRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPOSTTransactionsRequestWithTextBody calls the generic POSTTransactions builder with text/plain body
func NewPOSTTransactionsRequestWithTextBody(server string, params *POSTTransactionsParams, body POSTTransactionsTextRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyReader = strings.NewReader(string(body))
	return NewPOSTTransactionsRequestWithBody(server, params, "text/plain", bodyReader)
}

// NewPOSTTransactionsRequestWithBody generates requests for POSTTransactions with any type of body
func NewPOSTTransactionsRequestWithBody(server string, params *POSTTransactionsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/txs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XCallbackUrl != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-CallbackUrl", runtime.ParamLocationHeader, *params.XCallbackUrl)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-CallbackUrl", headerParam0)
		}

		if params.XSkipFeeValidation != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithLocation("simple", false, "X-SkipFeeValidation", runtime.ParamLocationHeader, *params.XSkipFeeValidation)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-SkipFeeValidation", headerParam1)
		}

		if params.XSkipScriptValidation != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithLocation("simple", false, "X-SkipScriptValidation", runtime.ParamLocationHeader, *params.XSkipScriptValidation)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-SkipScriptValidation", headerParam2)
		}

		if params.XCallbackToken != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithLocation("simple", false, "X-CallbackToken", runtime.ParamLocationHeader, *params.XCallbackToken)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-CallbackToken", headerParam3)
		}

		if params.XMerkleProof != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithLocation("simple", false, "X-MerkleProof", runtime.ParamLocationHeader, *params.XMerkleProof)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-MerkleProof", headerParam4)
		}

		if params.XWaitForStatus != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithLocation("simple", false, "X-WaitForStatus", runtime.ParamLocationHeader, *params.XWaitForStatus)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-WaitForStatus", headerParam5)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GETPolicyWithResponse request
	GETPolicyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GETPolicyResponse, error)

	// POSTTransactionWithBodyWithResponse request with any body
	POSTTransactionWithBodyWithResponse(ctx context.Context, params *POSTTransactionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*POSTTransactionResponse, error)

	POSTTransactionWithResponse(ctx context.Context, params *POSTTransactionParams, body POSTTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*POSTTransactionResponse, error)

	POSTTransactionWithTextBodyWithResponse(ctx context.Context, params *POSTTransactionParams, body POSTTransactionTextRequestBody, reqEditors ...RequestEditorFn) (*POSTTransactionResponse, error)

	// GETTransactionStatusWithResponse request
	GETTransactionStatusWithResponse(ctx context.Context, txid string, reqEditors ...RequestEditorFn) (*GETTransactionStatusResponse, error)

	// POSTTransactionsWithBodyWithResponse request with any body
	POSTTransactionsWithBodyWithResponse(ctx context.Context, params *POSTTransactionsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*POSTTransactionsResponse, error)

	POSTTransactionsWithResponse(ctx context.Context, params *POSTTransactionsParams, body POSTTransactionsJSONRequestBody, reqEditors ...RequestEditorFn) (*POSTTransactionsResponse, error)

	POSTTransactionsWithTextBodyWithResponse(ctx context.Context, params *POSTTransactionsParams, body POSTTransactionsTextRequestBody, reqEditors ...RequestEditorFn) (*POSTTransactionsResponse, error)
}

type GETPolicyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PolicyResponse
}

// Status returns HTTPResponse.Status
func (r GETPolicyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GETPolicyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type POSTTransactionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TransactionResponse
	JSON400      *ErrorBadRequest
	JSON422      *Error
	JSON465      *ErrorFee
	JSON466      *ErrorConflict
}

// Status returns HTTPResponse.Status
func (r POSTTransactionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r POSTTransactionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GETTransactionStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TransactionStatus
}

// Status returns HTTPResponse.Status
func (r GETTransactionStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GETTransactionStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type POSTTransactionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TransactionResponses
	JSON400      *ErrorBadRequest
}

// Status returns HTTPResponse.Status
func (r POSTTransactionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r POSTTransactionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GETPolicyWithResponse request returning *GETPolicyResponse
func (c *ClientWithResponses) GETPolicyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GETPolicyResponse, error) {
	rsp, err := c.GETPolicy(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGETPolicyResponse(rsp)
}

// POSTTransactionWithBodyWithResponse request with arbitrary body returning *POSTTransactionResponse
func (c *ClientWithResponses) POSTTransactionWithBodyWithResponse(ctx context.Context, params *POSTTransactionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*POSTTransactionResponse, error) {
	rsp, err := c.POSTTransactionWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePOSTTransactionResponse(rsp)
}

func (c *ClientWithResponses) POSTTransactionWithResponse(ctx context.Context, params *POSTTransactionParams, body POSTTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*POSTTransactionResponse, error) {
	rsp, err := c.POSTTransaction(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePOSTTransactionResponse(rsp)
}

func (c *ClientWithResponses) POSTTransactionWithTextBodyWithResponse(ctx context.Context, params *POSTTransactionParams, body POSTTransactionTextRequestBody, reqEditors ...RequestEditorFn) (*POSTTransactionResponse, error) {
	rsp, err := c.POSTTransactionWithTextBody(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePOSTTransactionResponse(rsp)
}

// GETTransactionStatusWithResponse request returning *GETTransactionStatusResponse
func (c *ClientWithResponses) GETTransactionStatusWithResponse(ctx context.Context, txid string, reqEditors ...RequestEditorFn) (*GETTransactionStatusResponse, error) {
	rsp, err := c.GETTransactionStatus(ctx, txid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGETTransactionStatusResponse(rsp)
}

// POSTTransactionsWithBodyWithResponse request with arbitrary body returning *POSTTransactionsResponse
func (c *ClientWithResponses) POSTTransactionsWithBodyWithResponse(ctx context.Context, params *POSTTransactionsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*POSTTransactionsResponse, error) {
	rsp, err := c.POSTTransactionsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePOSTTransactionsResponse(rsp)
}

func (c *ClientWithResponses) POSTTransactionsWithResponse(ctx context.Context, params *POSTTransactionsParams, body POSTTransactionsJSONRequestBody, reqEditors ...RequestEditorFn) (*POSTTransactionsResponse, error) {
	rsp, err := c.POSTTransactions(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePOSTTransactionsResponse(rsp)
}

func (c *ClientWithResponses) POSTTransactionsWithTextBodyWithResponse(ctx context.Context, params *POSTTransactionsParams, body POSTTransactionsTextRequestBody, reqEditors ...RequestEditorFn) (*POSTTransactionsResponse, error) {
	rsp, err := c.POSTTransactionsWithTextBody(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePOSTTransactionsResponse(rsp)
}

// ParseGETPolicyResponse parses an HTTP response from a GETPolicyWithResponse call
func ParseGETPolicyResponse(rsp *http.Response) (*GETPolicyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GETPolicyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PolicyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePOSTTransactionResponse parses an HTTP response from a POSTTransactionWithResponse call
func ParsePOSTTransactionResponse(rsp *http.Response) (*POSTTransactionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &POSTTransactionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TransactionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorBadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 465:
		var dest ErrorFee
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON465 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 466:
		var dest ErrorConflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON466 = &dest

	}

	return response, nil
}

// ParseGETTransactionStatusResponse parses an HTTP response from a GETTransactionStatusWithResponse call
func ParseGETTransactionStatusResponse(rsp *http.Response) (*GETTransactionStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GETTransactionStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TransactionStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePOSTTransactionsResponse parses an HTTP response from a POSTTransactionsWithResponse call
func ParsePOSTTransactionsResponse(rsp *http.Response) (*POSTTransactionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &POSTTransactionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TransactionResponses
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorBadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get the policy settings
	// (GET /v1/policy)
	GETPolicy(ctx echo.Context) error
	// Submit a transaction.
	// (POST /v1/tx)
	POSTTransaction(ctx echo.Context, params POSTTransactionParams) error
	// Get transaction status.
	// (GET /v1/tx/{txid})
	GETTransactionStatus(ctx echo.Context, txid string) error
	// Submit multiple transactions.
	// (POST /v1/txs)
	POSTTransactions(ctx echo.Context, params POSTTransactionsParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GETPolicy converts echo context to params.
func (w *ServerInterfaceWrapper) GETPolicy(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(Api_KeyScopes, []string{})

	ctx.Set(AuthorizationScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GETPolicy(ctx)
	return err
}

// POSTTransaction converts echo context to params.
func (w *ServerInterfaceWrapper) POSTTransaction(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(Api_KeyScopes, []string{})

	ctx.Set(AuthorizationScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params POSTTransactionParams

	headers := ctx.Request().Header
	// ------------- Optional header parameter "X-CallbackUrl" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CallbackUrl")]; found {
		var XCallbackUrl CallbackUrl
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-CallbackUrl, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-CallbackUrl", runtime.ParamLocationHeader, valueList[0], &XCallbackUrl)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-CallbackUrl: %s", err))
		}

		params.XCallbackUrl = &XCallbackUrl
	}
	// ------------- Optional header parameter "X-SkipFeeValidation" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-SkipFeeValidation")]; found {
		var XSkipFeeValidation SkipFeeValidation
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-SkipFeeValidation, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-SkipFeeValidation", runtime.ParamLocationHeader, valueList[0], &XSkipFeeValidation)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-SkipFeeValidation: %s", err))
		}

		params.XSkipFeeValidation = &XSkipFeeValidation
	}
	// ------------- Optional header parameter "X-SkipScriptValidation" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-SkipScriptValidation")]; found {
		var XSkipScriptValidation SkipScriptValidation
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-SkipScriptValidation, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-SkipScriptValidation", runtime.ParamLocationHeader, valueList[0], &XSkipScriptValidation)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-SkipScriptValidation: %s", err))
		}

		params.XSkipScriptValidation = &XSkipScriptValidation
	}
	// ------------- Optional header parameter "X-CallbackToken" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CallbackToken")]; found {
		var XCallbackToken CallbackToken
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-CallbackToken, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-CallbackToken", runtime.ParamLocationHeader, valueList[0], &XCallbackToken)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-CallbackToken: %s", err))
		}

		params.XCallbackToken = &XCallbackToken
	}
	// ------------- Optional header parameter "X-MerkleProof" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-MerkleProof")]; found {
		var XMerkleProof MerkleProof
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-MerkleProof, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-MerkleProof", runtime.ParamLocationHeader, valueList[0], &XMerkleProof)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-MerkleProof: %s", err))
		}

		params.XMerkleProof = &XMerkleProof
	}
	// ------------- Optional header parameter "X-WaitForStatus" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-WaitForStatus")]; found {
		var XWaitForStatus WaitForStatus
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-WaitForStatus, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-WaitForStatus", runtime.ParamLocationHeader, valueList[0], &XWaitForStatus)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-WaitForStatus: %s", err))
		}

		params.XWaitForStatus = &XWaitForStatus
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.POSTTransaction(ctx, params)
	return err
}

// GETTransactionStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GETTransactionStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "txid" -------------
	var txid string

	err = runtime.BindStyledParameterWithLocation("simple", false, "txid", runtime.ParamLocationPath, ctx.Param("txid"), &txid)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter txid: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(Api_KeyScopes, []string{})

	ctx.Set(AuthorizationScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GETTransactionStatus(ctx, txid)
	return err
}

// POSTTransactions converts echo context to params.
func (w *ServerInterfaceWrapper) POSTTransactions(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(Api_KeyScopes, []string{})

	ctx.Set(AuthorizationScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params POSTTransactionsParams

	headers := ctx.Request().Header
	// ------------- Optional header parameter "X-CallbackUrl" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CallbackUrl")]; found {
		var XCallbackUrl CallbackUrl
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-CallbackUrl, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-CallbackUrl", runtime.ParamLocationHeader, valueList[0], &XCallbackUrl)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-CallbackUrl: %s", err))
		}

		params.XCallbackUrl = &XCallbackUrl
	}
	// ------------- Optional header parameter "X-SkipFeeValidation" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-SkipFeeValidation")]; found {
		var XSkipFeeValidation SkipFeeValidation
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-SkipFeeValidation, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-SkipFeeValidation", runtime.ParamLocationHeader, valueList[0], &XSkipFeeValidation)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-SkipFeeValidation: %s", err))
		}

		params.XSkipFeeValidation = &XSkipFeeValidation
	}
	// ------------- Optional header parameter "X-SkipScriptValidation" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-SkipScriptValidation")]; found {
		var XSkipScriptValidation SkipScriptValidation
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-SkipScriptValidation, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-SkipScriptValidation", runtime.ParamLocationHeader, valueList[0], &XSkipScriptValidation)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-SkipScriptValidation: %s", err))
		}

		params.XSkipScriptValidation = &XSkipScriptValidation
	}
	// ------------- Optional header parameter "X-CallbackToken" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CallbackToken")]; found {
		var XCallbackToken CallbackToken
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-CallbackToken, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-CallbackToken", runtime.ParamLocationHeader, valueList[0], &XCallbackToken)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-CallbackToken: %s", err))
		}

		params.XCallbackToken = &XCallbackToken
	}
	// ------------- Optional header parameter "X-MerkleProof" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-MerkleProof")]; found {
		var XMerkleProof MerkleProof
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-MerkleProof, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-MerkleProof", runtime.ParamLocationHeader, valueList[0], &XMerkleProof)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-MerkleProof: %s", err))
		}

		params.XMerkleProof = &XMerkleProof
	}
	// ------------- Optional header parameter "X-WaitForStatus" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-WaitForStatus")]; found {
		var XWaitForStatus WaitForStatus
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-WaitForStatus, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-WaitForStatus", runtime.ParamLocationHeader, valueList[0], &XWaitForStatus)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-WaitForStatus: %s", err))
		}

		params.XWaitForStatus = &XWaitForStatus
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.POSTTransactions(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/v1/policy", wrapper.GETPolicy)
	router.POST(baseURL+"/v1/tx", wrapper.POSTTransaction)
	router.GET(baseURL+"/v1/tx/:txid", wrapper.GETTransactionStatus)
	router.POST(baseURL+"/v1/txs", wrapper.POSTTransactions)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbW3PbOJb+KyjuPiRVssWbSElV/eA48o63O3bWVrp3N+PqAsFDCxMS4ACgI3fW/30L",
	"4F2ibPmW7pkeP1nC7eA794OjbxbhWc4ZMCWt+TcrxwJnoECYTwSnaYTJlyX/Akx/EYMkguaKcmbNrSNC",
	"QEqk9ChKuECMK5pQgvU4qhcjYHHOKVOH1siiet0KcAzCGlkMZ2DNrf8+OO4dNLIkWUGG9YnqNtdTpBKU",
	"XVt3d6OGqE8i3SbpPSS4SBWKeRGlgGQOLEaYxSgD8SUFlAvOk+fTqc++n8ryvI/6uG0qf1mBWoFAiiPK",
	"SFrE0KNPIsqQWkFDmkRvlCgA/R9KcCrh7T0Ufuicez+F8gvNTwB+ximNcUnYAJ3YEPoVkFzxIo2RXoUS",
	"AHTTrEMl5+8h6nLrqAHSIs5TwKyh7dIQ8hTyyjmPpnDrwAeI/IqpOuHiUmFVyCHqKFkhaUY1p/V0oyWJ",
	"4JlhrwRxAwJFkHABSIAqBKPsGr1x0Q/oYnG8OP158X6EPPQDulyeX+j/ffQDOjo7O/90drx4/+vy/Nez",
	"xfKX84sfR2hi1vzXp8XlcvH+13f/044Eev3ibNmbHuqNjo8XHzdnT83sxdmv52f1l2934/ZLD4MBwChT",
	"cA3CutOICZA5ZxIMWmdcHRVqxQX9DeJt+C6BFIKqWyTg7wUVkGkThRJMU4hLGTFHma2OV5iyU5bw7W3M",
	"EKJ6bGTlgucgFC0JiFJOvvwFy9X2qnd6CK302MiCNc7yVF/G3vybTvzQn0UecdxJPHFJMPO9IAwnvk+m",
	"OMDT6cT1w5k3ifA0dsLYGm3q4aiiAuj1Su2koxztUBJOXc+ZjqyEiwwra24VlKnAb/dvYW++4tHfgCh9",
	"5DHPMs4uKmYMYGbGUc0tVK3cxE/RDKTCWa4/NJTEWMGBHtq+rJEAw8zYmn/urL8aIHIhBBcDPoehvyyX",
	"H9FHwaMUMvQeFKaprGgcISxRDAllEGsjerpYnqCLk2MUTu0QvVkplcv5eKw4T+UhBZUccnE9XqksHYuE",
	"6EnGtnIG54k1//zN+ncBiTW3/m3cuslxJXhjQ+EnpllE2XVpPaR1N9pj1SnLi33nfsCpBldL/T7TTwT/",
	"DdhHnlJy+5gVx5rVTBbSuruq4X+H4wv4ewHSiCZO031ROaGQxuX9+jITG3bp/1qtWq7AKDlIhSRAZqxl",
	"BCirL24cOMGMcaW/zwXXcYcBxKJMKswI9LesGY0FOVQYp4eEZ2PQlMmx43r+ZBLoxbIx3c1S37a1ylCV",
	"bmz5Dsc1lVajVLvOjKginDJ50z3Yt+0hfdwp/MecJSklr4u9wExiYpwklaXLHKGoUNpBCdDfYUQqQrRv",
	"Uus6ODGGCynI8hQreAYvvF2sCIJhVhz36Ul4weIn82T2KJ6cALy2KiQAEmEBSHGOUv71Gci6O5GdDCN7",
	"Ar1jnwSo+zhAS3jmu9Hp2/+fOLsGgTpfIp4gc3jPVVdI1sKq+nJe3bEyNFUMbjwGLuX6cMhVw1oJPBxm",
	"nJt/cIrMHBNvaH+oj8MRL9WppLIN/zLKymCqSFMcaap1kD9wbpf7/WPf1Oe+RT9R9kXfBxNVaDrMWZxV",
	"QeY+x8gdgazhEyI8hi7Cvu124g/K1EDw0ZGxzTSt+nQDSMG6jItrJm4RptZ0IEDsmq7T90itqKxuTSUS",
	"kIAQxkDwfe5eS/rGEbc5NOI1Ql+pWqG0wjnTMXuHzw+HO3q0RqRBe1RL+m4N2XDPr2h+TFiCygPRmyjF",
	"5EtKpUIZZlhrHamJQM0YxG9fw0CF7rCB6lL4VAsVPtJCdQOq3xH83FDw+sg7r4i88yjkqyj5+4U/lJkA",
	"CEVAcCHBWGlqiDAOmXF2AGsNPVOIC1NdUq/inndKf0kfrdOHJ3EheJz8t/nH92PEa4b+u1H3hlFvAOhG",
	"EU8G33sU+Fvp5T87D5zvwYO9zdAJwFHGC1bmYHFMy2jrYwdLU5HdKi3dKhiIpM6KLAKhI4pywj4FnJEl",
	"seJyRQf2K2nTYetlPWfPmlA3MJHt2pKsISQ6/u8+GBo2fLMyvC5plfQ3yKvlE1M2G+lBtZb0mueS6DvI",
	"eoLvzvxZELqzSTOpXe1UZbeRlVFG2XWVjVVoO2akRcvRF+3zZZCmTVQ/4DXNiqwuI+up6LM542pPju28",
	"3a6jWCMYkl4zrAoBSNNtIkv5uFMfvlg3GXrK7brY32eCWu3ZFLkhPuyGbftqXSJ2S2u3wrmf0dyojGq7",
	"+Qitb3G/74y6NLcBSbV4+zZXd6Ouaa4KnvvfqbP2sogyqqpivb5cR1071XDL2ihL273cVw9Xz1tYraqy",
	"eJvRzF2thp3isOXarndgewf2bOm4c9ub+9NDb+rOHHvi+P/b5ERz6/xH/WFdv6hYG+8QVp0KWsSOg4RA",
	"6Pjgu+4kcPzEtm0S4AmOY4yx4/kOJlE0I9PQcSaO48ckmfqJF0Yzf4JN8a/Pu3ty+8U9KX3XG412+1Lt",
	"Ok3otk8u2sX2vqS3fjLEaqVdwArWe2W6610PVt29m+wUWJFp8fx09uPZ+S9n1siqH6askVW+Slkja+hJ",
	"ykzdfo/Sy/qPUeabTUZ/OD0zOx+fn52cXnww/18s/nNxvFy810rSQl2/Yj25ctBg1+4ZRHFEEhzZEzeI",
	"PRumcTB1w1kSzuIkCZwk8m03wASmURh5bjid4cR2As8LYOInbmIPFgO2443dZMWVlm+UEPR1huxdZ2mn",
	"YN/RboG/LtfW3PprYdse6TqAFaxRSaQZg23VqNZuoniBv3YWP1j+KHd5kPgXsNj3Tm9eCh+aOWByH+kO",
	"9jIp/3AG4Zk69kCNbG1MZENS1+886Bkvuq/L30F6HiEKHYUzn6mCzPyz30vjDll8MP0rIapQw0Lg20FD",
	"1IexlYY/FoYv4qH/wZxvm/9W7vDFPFw4c0PX82LHjjGJJ4EdEIBJlNiROw2CaUKcmQOhZ9vuDBPwSZgQ",
	"34YYJjPsTt0J7KvK1V0eVN5eaHo/OmZmC1JfSnY9YlxuYeraztMfMJZVFb8ThsQxxOZhALKc8/RBgFqL",
	"avbaRkin/lUTzKVWnvKC7wALEEfFkICWYwgXagVM1Q1u/ZaIi5NjFIQTu27WMV1NZl1L8UqpvOzYoZW+",
	"pZRA5Zer3p/zHBh6d/kz+kkPEQ1GIdJO/aWqvWApOaGGkkMGasxzYAeRvDmothx3ULb0fkcXx9bIugEh",
	"y0s5h/ahrSfplTin1tzyzFcjS2ufAWV844zb7OsaBlppluZ9qGrxq5qtpLEQVWFdglKUXUvTAFLn3qc6",
	"2/iPxfJjnXf2Wphc2zZtkpwpqGpEeZ5WuI//JsumtbYn6uG0sDWjGv0NES5Mv6WGwredXfs1BI77DVZG",
	"nIosw+JWXwnU0N21COBrqcXzSBDrSi/S2Kp1md/KB4GlEhWyVARpei+RwF97FQfFES7fPs2rn3l8lSZP",
	"Kp9qGaxV3Vywwqp9KkVEAFYgDxFargCVzWio7VhFBDMUQXM+vwEhaFyW8a9THuG0uag+7JYXAh0JgmIs",
	"VxHHIjYEqRXIntsYkIiP55fLZc+xdBtndzjMdsq428O6y2F2pm+3au65aKulcY91/abfPRZ0W133mN5v",
	"m9RpUNVW847Hty+mTgMZkRbm7oacKFAHUgnAWX/jxitElGl9GczmYK3GeYrpBlGtR9gj19re+O6+rLCX",
	"brW+RAcbd08yTRWxZW208lv6No2dOEoF4PhWq0vr125wWvwZa0Zl7bN8CNuGqBzagY69/fdsejYAD73A",
	"dae/E+pNfPpiWN+NnqLpe3rPl3Pbm32SAydvdA4+xXePLN91X5bmIUo/sepxTycxSIeQ6hYdlH0v/Vba",
	"sieoreH4weRlyTuBQS5uNKj5QfCyxzY9lwNn99oOO1a56j/sxVdlOoNwd+Lh7uhq/E0rzt2ewWsnxrqu",
	"4jhSCAGszooQTxBGuYAbyguZ3lY5k+o/nw4GutuFgK3YZpO0fnfd6Xv0xnPNA6dpoH/b91rmdwQ6bm9/",
	"RVBlin1/dt9vV65eMQzfvv/LR+J6lT/wOszVoCyZWH2rPHCPNMmnButZkSqap7AZs8uXCNr/YDG7/FfQ",
	"/rsE7U3p87HR+0Ah848Vzf+VPS3if37ojuN4MyqtTVQTj37+04XrV3cjC+pfEbXI1E10vFCmi66LUN0W",
	"tU9jYLV+sDOwmm/1QcWCVB3KfuDN0cbHrtiUeyMb1d0sHSKsbtcVK9K0ZYsfeC3S2/eskMV2HMywGyc4",
	"Dh07DG2I3alLCHhOQCbhzE0Cx3ZwMLX9ALuBh50QOxhsNwgD2+mWfvdrd7t6VN70+YHEyYmniR9Frh/H",
	"My/2YeYQmLkBISGehU4EtjMlbjSN/SD2J0mylSUFzjT4p8mSrp6VJg3GNp2Mv/8Ln5EWbNxj2t65VOcl",
	"ulWxJ//sq6sAe/3Uq6MhJS/V1k+6HiHTtqlGv1h6+EBiZXvPq/RWmUgT2m0GSRsxZOfRwehi97nh85WO",
	"FI5yevAj3DYfq4Or32h/vtLBQfmjkzKq6r8KKJzTlk9YEC3E/x8AAP//5knz+IZAAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
