# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:
    branches: ["**"]
    paths:
      - 'cmd/**'
      - 'config/**'
      - 'internal/**'
      - 'pkg/**'
      - 'go.mod'
      - 'go.sum'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: GOEXPERIMENT=synctest go build -v ./...

      - name: Run go vet
        run: GOEXPERIMENT=synctest go vet ./...

      - name: Install code generation tools
        run: make install_gen

      - name: Check go format
        run: gofmt -s -w . && git diff --exit-code

      - name: Check go generate
        run: make gen_go && git diff --exit-code

      - name: Check generate api
        run: make api && git diff --exit-code

      - name: Check config
        run: make compare_config
