name: Static Analysis and Report

on:
  pull_request:
    branches: ["**"]
    paths:
      - 'cmd/**'
      - 'config/**'
      - 'internal/**'
      - 'examples/**'
      - 'pkg/**'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'

jobs:
  analyze:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"

      - name: Run unit tests
        run: go test -race -count=1 -vet=off -coverprofile=./cov.out ./... -tags=multicast_test -coverpkg ./...

      - name: Run gosec Security Scanner
        continue-on-error: true
        uses: securego/gosec@master
        with:
          args: -exclude-dir=testdata -exclude-dir=test -exclude-dir=blocktx/store/sql -exclude-generated -fmt=sonarqube -out gosec-report.json ./...

  staticcheck:
    name: Static check
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"

      - name: staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: v0.6.1
          install-go: false

  lint:
    name: Golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7

