name: Static Analysis and Report

on:
  pull_request:
    branches: ["**"]
    paths:
      - 'cmd/**'
      - 'config/**'
      - 'internal/**'
      - 'examples/**'
      - 'pkg/**'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'

jobs:
  analyze:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"

      - name: Run unit tests
        run: go test -race -count=1 -vet=off -coverprofile=./cov.out ./... -tags=multicast_test -coverpkg ./...

      - name: Run gosec Security Scanner
        continue-on-error: true
        uses: securego/gosec@master
        with:
          args: -exclude-dir=testdata -exclude-dir=test -exclude-dir=blocktx/store/sql -exclude-generated -fmt=sonarqube -out gosec-report.json ./...

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # Additional arguments for the SonarScanner CLI
          args:
            # Unique keys of your project and organization. You can find them in SonarCloud > Information (bottom-left menu)
            # mandatory
            -Dsonar.projectKey=bitcoin-sv_arc
            -Dsonar.organization=bitcoin-sv
            # Comma-separated paths to directories containing main source files.
            #-Dsonar.sources= # optional, default is project base directory
            # Comma-separated paths to directories containing test source files.
            #-Dsonar.tests= # optional. For more info about Code Coverage, please refer to https://docs.sonarcloud.io/enriching/test-coverage/overview/
          # Adds more detail to both client and server-side analysis logs, activating DEBUG mode for the scanner, and adding client-side environment variables and system properties to the server-side log of analysis report processing.
          #-Dsonar.verbose= # optional, default is false
          # When you need the analysis to take place in a directory other than the one from which it was launched, default is .
          projectBaseDir: .
  staticcheck:
    name: Static check
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"

      - name: staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: v0.6.1
          install-go: false

  lint:
    name: Golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7

